### ISSUE TITLE
still not working on window with ruby installed with msys2

### ISSUE THREAD

**Issue by ugur-kurnaz** [Shopify/ruby-lsp#1143]
### Ruby version

ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]

### Code snippet

any rb file, the lsp server just doesn't work

### Description

Ruby LSP> Trying to activate Ruby environment with command: ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))" inside directory: d:\projets\logic_games
Ruby LSP> Skipping lockfile copies because there's no top level bundle
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Could not find gem 'debug'.
C:/etc/msys64/ucrt64/lib/ruby/3.1.0/uri/generic.rb:760:in `check_path': bad component(expected absolute path component): d:/projets/logic_games (URI::InvalidComponentError)
	from C:/etc/msys64/ucrt64/lib/ruby/3.1.0/uri/generic.rb:806:in `path='
	from C:/etc/msys64/ucrt64/lib/ruby/3.1.0/uri/generic.rb:192:in `initialize'
	from C:/etc/msys64/ucrt64/lib/ruby/3.1.0/uri/generic.rb:136:in `new'
	from C:/etc/msys64/ucrt64/lib/ruby/3.1.0/uri/generic.rb:136:in `build'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/lib/core_ext/uri.rb:18:in `from_path'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11090/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/lib/ruby_lsp/utils.rb:9:in `<module:RubyLsp>'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/lib/ruby_lsp/utils.rb:4:in `<top (required)>'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/lib/ruby_lsp/internal.rb:14:in `require'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/lib/ruby_lsp/internal.rb:14:in `<top (required)>'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/exe/ruby-lsp:39:in `require_relative'
	from C:/etc/msys64/ucrt64/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.0/exe/ruby-lsp:39:in `<top (required)>'
	from C:/etc/msys64/ucrt64/bin/ruby-lsp:32:in `load'
	from C:/etc/msys64/ucrt64/bin/ruby-lsp:32:in `<main>'
[Error - 11:56:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:56:43 PM] Connection to server got closed. Server will restart.
true
[Error - 11:56:43 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:56:43 PM] Server process exited with code 1.

...

[Error - 11:57:09 PM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### Expected output

don't know, it's been a while I'm trying to use this. But actually, I'm not sure what to except from a "had never worked" extension.

**Comment by ugur-kurnaz** [comment]
ok finally got it begin to work, but much more requirement than stated

gem install debug
gem install prism
gem install ruby-lsp

also those gems strangely fail to install in windows terminal like other. I was forced to install them in a full ucrt64 (or mingw64) msys2 shell.

you might also need to delete .ruby-lsp folder and restart vscode to have it properly starting.
