### ISSUE TITLE
cannot start ruby-lsp

### ISSUE THREAD

**Issue by ibotty** [Shopify/ruby-lsp#1266]
### Ruby version

3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

### Code snippet

```shell
> ruby-lsp
Ruby LSP> Skipping custom bundle setup since /var/home/tob/src/project/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
The Gemfile's dependencies are satisfied
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
bundler: failed to load command: ruby-lsp (/var/home/tob/bin/ruby-lsp)
/var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/rubygems_integration.rb:362:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/rubygems_integration.rb:390:in `block in replace_bin_path'
        from /var/home/tob/bin/ruby-lsp:25:in `<top (required)>'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `load'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:28:in `run'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli.rb:474:in `exec'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        from /var/home/tob/src/project/.ruby-lsp/bundle/ruby/3.2.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
```

### Description

Anything I can do?

### Expected output

it works

**Comment by henrahmagix** [comment]
I managed to fix this by removing the local bundler config I had that set BUNDLE_BIN to a local bin folder, then I cleaned up everything and restarted and it worked!
```
$ cat .bundle/config
---
BUNDLE_BIN: "bin"

$ rm -r .bundle
$ bundle clean --force
Removing language_server-protocol (3.17.0.3)
Removing prism (0.19.0)
Removing ruby-lsp (0.13.2)
Removing sorbet-runtime (0.5.11163)
$ cat .ruby-version
3.2.2
$ cat .ruby-gemset
my-test-project
$ git checkout Gemfile.lock
$ bundle install
```

then I restarted VS Code so the extension setup everything, and finally
```
$ ruby-lsp
Ruby LSP> Skipping custom bundle setup since /me/my-test-project/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
Starting Ruby LSP v0.13.2...
```
