### ISSUE TITLE
ruby-lsp on rails/rails checkout

### ISSUE THREAD

**Issue by zzak** [Shopify/ruby-lsp#1272]
### Ruby version

3.2.2

### Code snippet

```
git clone https://github.com/rails/rails
code rails
```

### Description

Sorry if this is not necessarily a ruby-lsp bug.

```
2023-12-28 08:03:42.221 [info] Discovered Ruby version 3.2.2
2023-12-28 08:03:42.244 [info] Found Ruby installation in /Users/zzak/.rbenv/versions/3.2.2/bin
2023-12-28 08:03:42.398 [info] Activated Ruby environment: gem_home=/Users/zzak/.gem/ruby/3.2.0, version=3.2.2, yjit=null, gem_root=/Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
2023-12-28 08:03:43.211 [info] Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2023-12-28 08:03:43.518 [info] https://github.com/matthewd/websocket-client-simple.git (at close-race@e161305)
is not yet checked out. Run `bundle install` first.

2023-12-28 08:03:43.858 [info] Fetching https://github.com/matthewd/websocket-client-simple.git

2023-12-28 08:03:48.685 [info] Fetching https://github.com/rails/sdoc.git

2023-12-28 08:03:52.422 [info] Fetching gem metadata from https://rubygems.org/.
2023-12-28 08:03:52.589 [info] .
2023-12-28 08:03:52.598 [info] .
2023-12-28 08:03:52.648 [info] .
2023-12-28 08:03:52.669 [info] .
2023-12-28 08:03:52.677 [info] .
2023-12-28 08:03:52.685 [info] .
2023-12-28 08:03:52.685 [info] .
2023-12-28 08:03:52.686 [info] .
2023-12-28 08:03:53.131 [info] 

2023-12-28 08:03:53.217 [info] Resolving dependencies...

2023-12-28 08:03:53.675 [info] Your bundle is locked to actionpack (7.2.0.alpha) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of actionpack (7.2.0.alpha) has
removed it. You'll need to update your bundle to a version other than actionpack
(7.2.0.alpha) that hasn't been removed in order to install.

2023-12-28 08:03:54.202 [info] bundler: failed to load command: ruby-lsp (/Users/zzak/.gem/ruby/3.2.0/bin/ruby-lsp)

2023-12-28 08:03:54.203 [info] /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/resolver.rb:116:in `rescue in solve_versions': Could not find compatible versions (Bundler::SolveFailure)

Because every version of rails depends on actiontext = 7.2.0.alpha
  and actiontext = 7.2.0.alpha could not be found in locally installed gems,
  rails cannot be used.
So, because Gemfile depends on rails >= 0,
  version solving has failed.
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/resolver.rb:79:in `solve_versions'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/resolver.rb:32:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:570:in `start_resolution'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:301:in `resolve'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:523:in `materialize'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:200:in `specs'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:266:in `specs_for'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/runtime.rb:18:in `setup'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler.rb:162:in `setup'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/setup.rb:23:in `<top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:492:in `exec'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/zzak/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
/Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:237:in `resolve_conflict': Could not find compatible versions (Bundler::PubGrub::SolveFailure)

Because every version of rails depends on actiontext = 7.2.0.alpha
  and actiontext = 7.2.0.alpha could not be found in locally installed gems,
  rails cannot be used.
So, because Gemfile depends on rails >= 0,
  version solving has failed.
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:73:in `block in propagate'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `reverse_each'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:70:in `propagate'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:42:in `work'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/pub_grub/lib/pub_grub/version_solver.rb:58:in `solve'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/resolver.rb:81:in `solve_versions'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/resolver.rb:32:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:570:in `start_resolution'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:301:in `resolve'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:523:in `materialize'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:200:in `specs'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/definition.rb:266:in `specs_for'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/runtime.rb:18:in `setup'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler.rb:162:in `setup'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/setup.rb:23:in `<top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:492:in `exec'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:
2023-12-28 08:03:54.203 [info] in `with_friendly_errors'
	from /Users/zzak/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
	from /Users/zzak/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/zzak/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

2023-12-28 08:03:54.205 [info] [Error - 8:03:54] Server process exited with code 1.
2023-12-28 08:03:54.205 [info] [Error - 8:03:54] Server initialization failed.
2023-12-28 08:03:54.206 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-12-28 08:03:54.206 [info] [Info  - 8:03:54] Connection to server got closed. Server will restart.
2023-12-28 08:03:54.206 [info] true
2023-12-28 08:03:54.206 [info] [Error - 8:03:54] Ruby LSP client: couldn't create connection to server.
2023-12-28 08:03:54.206 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-12-28 08:03:54.430 [info] Ruby LSP> Skipping custom bundle setup since /Users/zzak/code/rails/.ruby-lsp/Gemfile.lock already exists and is up to date
```

As a side note, while I'm here, it was interesting to see ruby-lsp fail to discover the version of ruby when `~/.ruby-version` was simply "trunk" because I've been installing trunk to `~/.rbenv/versions/trunk` for a while.

To be fair, I don't think this has ever worked though, and I might be the only one so also curious if/how others have dealt with this. :bow:

### Expected output

What do you normally expect when the LSP starts up properly?

**Comment by andyw8** [comment]
Thanks for the report @zzak. I wasn't yet able to reproduce – does `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle` succeed for you?

**Comment by zzak** [comment]
> does BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle succeed for you?

Am I supposed to run that in the terminal of vscode? FWIW, I also tried just adding `ruby-lsp` to the rails/rails Gemfile and the same error occurs.

**Comment by st0012** [comment]
Hmm I also couldn't reproduce this. And I've worked with `rails/rails` on and off in the past few months and didn't see similar errors before.

@zzak Can you try this:

1. Run `bundle install` in `rails/rails` root
2. Run `cmd + shift + p` in VS Code and run `Developer: Reload Window`

And then see if the problem still occurs?

**Comment by zzak** [comment]
Sorry for disappearing, this wasn't an immediate blocker for me and was busy with other stuff.

Thank you for looking into it, and I will try to circle back and give it a try again. 🙇
