### ISSUE TITLE
Ruby LSP cannot handle valid 'textDocument/didChange' event

### ISSUE THREAD

**Issue by puremourning** [Shopify/ruby-lsp#1273]
### Ruby version

3.2.2

### Code snippet

Any code.

```
self
```

### Description

LSP specification: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange

The didChange event may be:

- an object with a range, rangeLength, and text, OR
- just text

Ruby LSP server fails with a client which sends the later.

Here is the output:

```
2023-12-28 16:56:10,057 - DEBUG - TX: Sending notification: b'Content-Length: 193\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"p self.class\\n\\nx \\n"}],"textDocument":{"uri":"file:///Users/ben/Development/ruby/test.rb","version":7}}}'


2023-12-28 16:56:10,059 - DEBUG - RX: Received message: b'{"id":null,"error":{"code":-32603,"message":"#<NoMethodError: undefined method `[]\' for nil:NilClass>","data":{"errorClass":"NoMethodError","errorMessage":"undefined method `[]\' for nil:NilClass","backtrace":"~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/document.rb:85:in `block in push_edits\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/document.rb:81:in `each\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/document.rb:81:in `push_edits\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/store.rb:68:in `push_edits\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:342:in `text_document_did_change\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:82:in `run\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:26:in `execute\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:68:in `block in start\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:65:in `start\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/sorbet-runtime-0.5.11164/lib/types/private/methods/_methods.rb:274:in `bind_call\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/sorbet-runtime-0.5.11164/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/vendor/bundle/ruby/3.2.0/gems/ruby-lsp-0.13.2/exe/ruby-lsp:111:in `<top (required)>\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/bin/ruby-lsp:27:in `load\'\\n~/.vim/bundle/lsp-examples/ruby-lsp/bin/ruby-lsp:27:in `<main>\'"}},"jsonrpc":"2.0"}'

```

Based on the stack trace, it seems that Ruby LSP is assuming that didChange events will have `range`:

```
    def push_edits(edits, version:)
      edits.each do |edit|
        range = edit[:range]

```

Further, the above "error" message doesn't seem to be valid. It doesn't contain any 'method', and has a NULL ID.

### Expected output

Ruby LSP should respect the protocol and allow `textDocument/didChange` such as the following:

```
2023-12-28 16:56:10,057 - DEBUG - TX: Sending notification: b'Content-Length: 193\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"p self.class\\n\\nx \\n"}],"textDocument":{"uri":"file:///Users/ben/Development/ruby/test.rb","version":7}}}'

```

**Comment by vinistock** [comment]
Thank you for the bug report!

### Text synchronization

My understanding of the text synchronization event is a bit different. The TypeScript type definition indeed accepts both, but it's the server that determines which type of synchronization it wants to accept.

As it says on the [server capability](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncKind), if the server specifies that it wants `incremental` text changes, then the client should only send those. And if the server selects `full` text synchronization, then the client should send the full text.

Excerpt from the spec:
```
/**
* Defines how the host (editor) should sync document changes to the language
* server.
*/
```

A little [further above in the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_synchronization), it explicitly mentions that clients must implement both full and incremental text synchronization and cannot opt-out.

```
Client support for [textDocument/didOpen](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen), [textDocument/didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) and [textDocument/didClose](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didClose) notifications is mandatory in the protocol and clients can not opt out supporting them. This includes both full and incremental synchronization in the [textDocument/didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) notification.
```

So, I believe the client you're using is not respecting the server's synchronization preference - given that the Ruby LSP always prefers incremental text synchronization. What editor are you using? It's likely this is a bug in their LSP client implementation.

### Signature help

We check if the active signature help is `nil` [here](https://github.com/Shopify/ruby-lsp/blob/fa551180d8be4e9e8e439f98c44a894de09df6c9/lib/ruby_lsp/executor.rb#L264), so I'm not sure what's happening. In what situation is this failing? How do you cause the failure to happen?

**Comment by puremourning** [comment]
That said, LSP owner just clarified that range is indeed optional : https://github.com/microsoft/language-server-protocol/issues/1870#issuecomment-1881609141

**Comment by vinistock** [comment]
I think that response is just saying that the specification supports an option that doesn't include the range.

If the LSP team says something like "clients may decide to send the full text even if the server asked for incremental text synchronization", then that's different. But if that's the case, then what's the point of the server capability? Every server would be forced to always support both styles of synchronization anyway, so the text synchronization capability would not matter at all.

Also, regarding the signature help thing, I think it's fixed by https://github.com/Shopify/ruby-lsp/pull/1285, so I'll close this one.
