### ISSUE TITLE
LSP showing error

### ISSUE THREAD

**Issue by tachyons** [Shopify/ruby-lsp#1345]
### Ruby version

3.2

### Code snippet

```
[ERROR][2024-02-01 20:46:42] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/apple/.asdf/shims/ruby-lsp"	"stderr"	"undefined method `[]' for nil:NilClass\n"
[DEBUG][2024-02-01 20:46:42] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  error = {    code = -32603,    data = {      backtrace = "~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:254:in `signature_help'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11144/lib/types/private/methods/_methods.rb:277:in `bind_call'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11144/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:176:in `run'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:26:in `execute'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:135:in `block (2 levels) in new_worker'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:123:in `loop'\n~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:123:in `block in new_worker'",      errorClass = "NoMethodError",      errorMessage = "undefined method `[]' for nil:NilClass"    },    message = "#<NoMethodError: undefined method `[]' for nil:NilClass>"  },  id = 8,  jsonrpc = "2.0"}
```

### Description

LSP showing undefined method for NilClass in Neovim

### Expected output

Work without showing any error messages

**Comment by snutij** [comment]
Hello @tachyons, reading your stack trace, I can see that you are using ruby-lsp `v0.13.2`.
Your issue seems pretty similar to https://github.com/Shopify/ruby-lsp/issues/1284. Which has been fixed with the [`v0.13.3`](https://github.com/Shopify/ruby-lsp/releases/tag/v0.13.3). 

Could you try to update to the latest version of the ruby-lsp gem and see if you still have this issue?
