### ISSUE TITLE
Raise response exceptions in IntegrationTest for better exception reporting

### ISSUE THREAD

**Issue by wildmaples** [Shopify/ruby-lsp#163]
## What is the problem we're trying to solve?

While working on [this PR](https://github.com/Shopify/ruby-lsp/pulls), I noticed that `IntegrationTest` does not surface any errors found while reading the response in `#read_response`. 

## Why is this a problem we need to solve?

Better exception reporting and therefore ✨ PRODUCTIVITY ✨ 

The problem is that, when there is an error, the `:result` key in the response is `nil`, and that causes the test to fail without a useful error message. For example, this is a test exception where the `response` object is nil: 

```
Minitest::UnexpectedError:         NoMethodError: undefined method `dig' for nil:NilClass

            assert(true, response.dig(:capabilities, :textDocumentSync, :openClose))
                                 ^^^^
            /Users/mapleong/src/github.com/Shopify/ruby-lsp/test/integration_test.rb:258:in `initialize_lsp'
            /Users/mapleong/src/github.com/Shopify/ruby-lsp/test/integration_test.rb:74:in `test_semantic_highlighting'
```

The reason why it's nil is because the response object's `:result` key is nil, but for a different reason than the one stated above. We would have to investigate it deeper after seeing this message. 

However, if we just had the error message from this JSON surface, the problem would be immediately obvious: 

```ruby
  { "method": "telemetry/event",
    "params": { "request": "initialize",
                "lspVersion": "0.1.0",
                "requestTime": 0.001909999642521143, "errorClass": "NameError", "errorMessage": "uninitialized constant RubyLsp::Requests::SemanticHighlighting::Set\n\n      SPECIAL_RUBY_METHODS = T.let(Set[\n                                   ^^^", }, "jsonrpc": "2.0", }
```

## How do you propose we solve it?

Raise the errors immediately if there is one, and show the underlying error message.

**Comment by st0012** [comment]
After https://github.com/Shopify/ruby-lsp/pull/160, the LSP server will return a error response with the exception info. So the response won't be `nil` anymore.
