### ISSUE TITLE
server crashes when using private GitHub RubyGems package registries

### ISSUE THREAD

**Issue by GrantBirki** [Shopify/ruby-lsp#1712]
### Operating System

Ubuntu

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

I only just started using this new VSC extension because the old one I was using is now deprecated. I get the following error when opening any project that has internal Gems (from work) in the project. These "internal" gems are hosted in GitHub's RubyGems package registry instead of on RubyGems.org.

GitHub's RubyGems package registry documentation is available [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry) in case the person who takes a look at this issue is unfamiliar.

When opening projects that have these Gems, the Ruby LSP server instantly fails. I have ruled out there being something wrong with my `ruby-lsp` configuration because if I open a project that does not contain internal Gems from our internal package registry, everything works just fine. The issue is consistent with projects that have internal Gems. I am guessing that something isn't working correctly when `ruby-lsp` tries to `bundle install` and setup its own dependencies. Perhaps it doesn't inherit the permissions that are needed to pull Gems from `rubygems.pkg.github.com/NAMESPACE`.

I use the following command to authenticate with the GitHub RubyGems package registry to pull down internal Gems for my project:

```console
$ bundle config --global https://rubygems.pkg.github.com/NAMESPACE USERNAME:TOKEN
```

ruby-lsp error that I get when opening VSC for a Ruby project:

> Example: `code .`

```text
Ruby LSP> Skipping custom bundle setup since /home/grantbirki/code/<redacted>/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.pkg.github.com/<redacted>/..
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler could not find compatible versions for gem
"<redacted>":
  In snapshot (Gemfile.lock):
    <redacted> (= 0.5.2)

  In Gemfile:
    <redacted> (~> 0.5)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your
snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "<redacted>":
  In Gemfile:
<redacted> (~> 0.5) was resolved to 0.5.2, which
depends on
      <redacted> (= 0.3.4.gffe2410)

Could not find gem '<redacted> (= 0.3.4.gffe2410)', which is required by
gem '<redacted> (~> 0.5)', in rubygems repository
https://rubygems.pkg.github.com/<redacted>/.

The source contains the following gems matching '<redacted>':
  * <redacted>-0.4.0
bundler: failed to load command: ruby-lsp (/home/grantbirki/.rbenv/versions/3.2.2/bin/ruby-lsp)
/home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:271:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'aws-sdk-ec2 (~> 1)' in locally installed gems. (Bundler::GemNotFound)
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:254:in `map!'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:254:in `verify_gemfile_dependencies_are_found!'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:49:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:24:in `resolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:480:in `reresolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:283:in `resolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:488:in `materialize'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:191:in `specs'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:247:in `specs_for'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:18:in `setup'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler.rb:163:in `setup'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:136:in `with_level'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:88:in `silence'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/setup.rb:20:in `<top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:23:in `run'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:483:in `exec'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:31:in `dispatch'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:25:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/exe/bundle:48:in `block in <top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/exe/bundle:36:in `<top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:00:18 PM] Server process exited with code 1.
[Error - 12:00:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:00:18 PM] Connection to server got closed. Server will restart.
true
[Error - 12:00:18 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by vinistock** [comment]
I'm not sure why this is the case. We use private gems as well with the authentication set in our Bundler config and everything works seamlessly. As long as `bundle install` passes in the terminal, it should also work in the extension.

Are any of you setting the authentication configuration in shell scripts/configuration files such as `~/.zshrc`? Because the process spawned by the extension to run `bundle install` does not try to source shell files and would not pick up on configuration set there.
