### ISSUE TITLE
ruby-lsp Crashes: can't find executable ruby-lsp for gem ruby-lsp

### ISSUE THREAD

**Issue by truecar-mvelez** [Shopify/ruby-lsp#1713]
### Operating System

macOS 13.6

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

other (please specify in description)

### Description

I installed this extension as the main Ruby one is now depreciated, and I use `rtx` to manage my Ruby versions.

I keep getting the below error every time VSCode starts up.

I've followed the troubleshooting guide (and ensured the `rtx` eval command is in my settings. I already had the `ruby-lsp` gem installed, and even after uninstalling it and deleting the `.ruby-lsp/` directory, the issue persists.

I can verify that `/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp` does exist and works properly when executed outside the project. The project's `Gemfile` doesn't use `ruby-lsp` at all, nor does it show up in `Gemfile.lock`.

Not sure what else I could be doing, maybe it's a problem with my VSCode install or settings?

---

```
Ruby LSP> Trying to activate Ruby environment with command: /usr/local/bin/bash -ic 'eval "$(rtx env -s bash)" && ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /Users/mvelez/code/pr-report
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:12 PM] Server process exited with code 1.
[Error - 12:47:12 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:12 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:12 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:14 PM] Server process exited with code 1.
[Error - 12:47:14 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:14 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:14 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
Error restarting the server: Pending response rejected since connection got disposed
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:17 PM] Server process exited with code 1.
[Error - 12:47:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:17 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:17 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:18 PM] Server process exited with code 1.
[Error - 12:47:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:18 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:18 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:20 PM] Server process exited with code 1.
[Error - 12:47:20 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:20 PM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 12:47:20 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:20 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by lcmen** [comment]
I've encountered the same issue. When I run:

```
BUNDLE_GEMFILE=/path/to/my/app/.ruby-lsp/Gemfile BUNDLE_PATH=/path/to/my/app/vendor/bundle BUNDLE_APP_CONFIG=/path/to/my/app/.bundle bundle exec ruby-lsp
```

lsp server starts fine, but when I run `ruby-lsp`, it throws error:

```
bundler: failed to load command: ruby-lsp (/path/to/my/app/vendor/bundle/ruby/3.3.0/bin/ruby-lsp)
/path/to/my/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.3/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```

What I was able to identify is that when [the initial process is replaced with `bundle exec`](https://github.com/Shopify/ruby-lsp/blob/main/exe/ruby-lsp#L76), the `BUNDLE_GEMFILE` env is not carried over to the new process (it points to `/path/to/my/app/Gemfile` instead of `/path/to/my/app/.ruby-lsp/Gemfile`).

Here is the output of `bundle config` command:

```
build.pg
Set for the current user (/Users/lucas/.config/bundle/config): "--with-pg-config=/opt/homebrew/opt/libpq/bin/pg_config"

build.puma
Set for your local app (/path/to/my/app/.bundle/config): "--with-opt-dir=/opt/homebrew/opt/openssl@1.1"

gem.changelog
Set for the current user (/Users/lucas/.config/bundle/config): false

gem.ci
Set for the current user (/Users/lucas/.config/bundle/config): "github"

gem.coc
Set for the current user (/Users/lucas/.config/bundle/config): false

gem.linter
Set for the current user (/Users/lucas/.config/bundle/config): "rubocop"

gem.mit
Set for the current user (/Users/lucas/.config/bundle/config): false

gem.test
Set for the current user (/Users/lucas/.config/bundle/config): "rspec"

github.com
Set for your local app (/path/to/my/app/platform/.bundle/config): "x-access-token:[REDACTED]"

path
Set for your local app (/path/to/my/app/.bundle/config): "/path/to/my/app/vendor/bundle"
Set for the current user (/Users/lucas/.config/bundle/config): "./vendor/bundle"

user_home
Set via BUNDLE_USER_HOME: "/Users/lucas/.config/bundle"

```

@vinistock any ideas?

**Comment by vinistock** [comment]
@lcmen what editor are you using? How is the executable command configured?

It's odd that you're trying to run the `ruby-lsp` executable from inside `vendor/bundle`. If you're invoking `ruby-lsp`, then the gem should be installed globally with `gem install ruby-lsp`.

And if the gem is a part of your bundle, then you should be running `bundle exec ruby-lsp`, which fully avoids the process replacement.

**Comment by lcmen** [comment]
@vinistock I'm testing it from the terminal.

> It's odd that you're trying to run the ruby-lsp executable from inside vendor/bundle. If you're invoking ruby-lsp, then the gem should be installed globally with gem install ruby-lsp.

I'm not trying to run the executable from `vendor/bundle`. I've installed it globally (via `gem install ruby-lsp`). However it does not work when I run it as `ruby-lsp` - specifically because the `BUNDLE_GEMFILE` is not correctly set.

**Comment by lcmen** [comment]
> > I'm testing it from the terminal.
> 
> Why? What are you trying to do?

I'm trying to debug because it does not work from Neovim with exact same error :)

> When invoked without `bundle exec`, we set `BUNDLE_GEMFILE` [here](https://github.com/Shopify/ruby-lsp/blob/a5e17758c74c6559b13a715f20d81ee212fb21f6/exe/ruby-lsp#L73). It would be useful to know
> 
> * What did we discover as the `BUNDLE_GEMFILE`?

I compared `ENV` output from `exe/ruby-lsp` file and `vendor/bundle/ruby/3.3.0/bin/ruby-lsp`.

> * Are you running the `ruby-lsp` command from inside the same directory where your `Gemfile` exists?

Yes, I'm running it from my app directory with it's own Gemfile. `ruby-lsp` creates `.ruby-lsp` folder with its Gemfile which merges with my application's Gemfile.

**Comment by tomocrafter** [comment]
I'm on the same boat with ruby 3.3.4 and mise.
Running `ruby-lsp` shows following error:
```
bundler: failed to load command: ruby-lsp (/home/tomo/.local/share/mise/installs/ruby/3.3.4/bin/ruby-lsp)
/home/tomo/Repositories/Work/projectname/.ruby-lsp/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.16/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```
But running `BUNDLE_GEMFILE=.ruby-lsp/Gemfile ruby-lsp` works as expected (It does not output anything at default but it shows bunch of `indexing` with `--doctor`).
I suspect that this issue occuring because I have `.bundle/config` with
```
---
BUNDLE_PATH: "vendor/bundle"
```
Even though it was working on ruby 3.2.4, It started to not work when I upgrade ruby to 3.3.4. Can I specify the `BUNDLE_GEMFILE` on vscode extension?

**Comment by vinistock** [comment]
I think the issue reported by @lcmen and @tomocrafter will be fixed by #2535. It was a regression when we added support for project-level Bundler settings.

**Comment by lcmen** [comment]
Thanks @vinistock for the follow-up! Is the fix from #2535 included in `0.7.20` version or it will be available in the next release?

**Comment by vinistock** [comment]
0.7.20 is the VS Code extension server, but this fix is on the server side (the Ruby gem `ruby-lsp`). It will be available in the next release, which will either be `v0.17.18` or `v0.18.0`, depending on whether breaking changes are merged into main.

**Comment by tomocrafter** [comment]
I updated ruby-lsp to 0.18.1 which includes #2535 fix but vscode extension failed to start with exactly same error. I guess there is another issue preventing from start lsp. How can I help to investigate the issue?
Thank you.
