### ISSUE TITLE
Header must provide a Content-Length property

### ISSUE THREAD

**Issue by jcagarcia** [Shopify/ruby-lsp#1723]
### Operating System

OSX Sonoma 14.0

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

After opening a Ruby project using VSCode, I'm getting the following error when trying to initialize the Ruby LSP extension

```
Ruby LSP> Skipping custom bundle setup since /Users/Juancarlos.Garcia/code/my-project/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
The Gemfile's dependencies are satisfied
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Bundler attempted to update ruby-lsp but its version stayed the same
Bundler attempted to update debug but its version stayed the same
Bundle updated!
Starting Ruby LSP...
[Error - 20:47:53] Client Ruby LSP: connection to server is erroring.
Header must provide a Content-Length property.
{"resolving dependencies...\ncontent-length":"1539"}
Shutting down server.
[Error - 20:47:53] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at $d.shutdown (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:41:8468)
	at $d.stop (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:41:8047)
	at $d.stop (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:44:38188)
	at $d.handleConnectionError (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:47:53] Client Ruby LSP: connection to server is erroring.
Header must provide a Content-Length property.
{"{\"id\"":"0,\"result\":{\"capabilities\":{\"positionEncoding\":\"utf-16\",\"textDocumentSync\":{\"openClose\":true,\"change\":2},\"completionProvider\":{\"triggerCharacters\":[\"/\",\"A\",\"B\",\"C\",\"D\",\"E\",\"F\",\"G\",\"H\",\"I\",\"J\",\"K\",\"L\",\"M\",\"N\",\"O\",\"P\",\"Q\",\"R\",\"S\",\"T\",\"U\",\"V\",\"W\",\"X\",\"Y\",\"Z\"],\"completionItem\":{\"labelDetailsSupport\":true}},\"hoverProvider\":{},\"definitionProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":{\"symbolKind\":{\"value_set\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},\"hierarchicalDocumentSymbolSupport\":true},\"codeActionProvider\":{\"resolveProvider\":true},\"codeLensProvider\":{},\"documentLinkProvider\":{},\"documentFormattingProvider\":true,\"documentOnTypeFormattingProvider\":{\"firstTriggerCharacter\":\"{\",\"moreTriggerCharacter\":[\"\\n\",\"|\"]},\"foldingRangeProvider\":{\"lineFoldingOnly\":true},\"selectionRangeProvider\":true,\"semanticTokensProvider\":{\"documentSelector\":{\"scheme\":\"file\",\"language\":\"ruby\"},\"legend\":{\"tokenTypes\":[\"namespace\",\"type\",\"class\",\"enum\",\"interface\",\"struct\",\"typeParameter\",\"parameter\",\"variable\",\"property\",\"enumMember\",\"event\",\"function\",\"method\",\"macro\",\"keyword\",\"modifier\",\"comment\",\"string\",\"number\",\"regexp\",\"operator\",\"decorator\"],\"tokenModifiers\":[\"declaration\",\"definition\",\"readonly\",\"static\",\"deprecated\",\"abstract\",\"async\",\"modification\",\"documentation\",\"default_library\"]},\"range\":true,\"full\":{\"delta\":false}},\"inlayHintProvider\":{},\"diagnosticProvider\":{\"interFileDependencies\":false,\"workspaceDiagnostics\":false},\"workspaceSymbolProvider\":true}},\"jsonrpc\":\"2.0\"}Content-Length: 242"}
Shutting down server.
[Error - 20:47:53] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at $d.shutdown (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:41:8468)
	at $d.stop (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:41:8047)
	at $d.stop (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:44:38188)
	at $d.handleConnectionError (/Users/Juancarlos.Garcia/.vscode/extensions/shopify.ruby-lsp-0.4.10/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by thatbudakguy** [comment]
I seem to be having this same issue, but the setup is quite different:

- using rbenv, not rvm
- using extension version v0.7.11 with bundler 2.5.14
- using vscode 1.91.0

The LSP starts up fine and correctly detects my shell, version manager, etc. The problem only occurs when I ask it to format a file using the VSCode command palette:

```
2024-07-10 13:43:35.668 [info] (geoblacklight) [Error - 1:43:35 PM] Client Ruby LSP: connection to server is erroring.
Header must provide a Content-Length property.
{"inspecting 1 file\n\n\n1 file inspected, no offenses detected\ncontent-length":"39"}
Shutting down server.
2024-07-10 13:43:35.669 [info] (geoblacklight) Shutting down Ruby LSP...

2024-07-10 13:43:35.669 [info] (geoblacklight) [Error - 1:43:35 PM] Client Ruby LSP: connection to server is erroring.
Header must provide a Content-Length property.
{"{\"id\"":"41,\"result\":null,\"jsonrpc\":\"2.0\"}Content-Length: 39"}
Shutting down server.
2024-07-10 13:43:37.670 [info] (geoblacklight) [Error - 1:43:37 PM] Stopping server timed out
2024-07-10 13:43:37.674 [info] (geoblacklight) [Error - 1:43:37 PM] Stopping server failed
2024-07-10 13:43:37.675 [info] (geoblacklight) Error: Stopping the server timed out
```

It looks like the output of rubocop is being mixed in, but:
- I don't have the rubocop extension installed or configured
- This project uses standardrb, and the LSP correctly detected that

Could this be a problem with the Standard Ruby LSP addon? I noticed that I don't encounter this problem on other projects that do use the LSP but use rubocop instead of standardrb.

**Comment by andyw8** [comment]
@thatbudakguy could you create a separate issue for this please? It could be something quite different, and there's been a lot of changes since this was originally opened.
