### ISSUE TITLE
LSP vscode plugin crashed after upgrading to v0.5.16

### ISSUE THREAD

**Issue by cyhsujohn** [Shopify/ruby-lsp#1858]
### Description

Hi, I just upgraded my LSP version to v0.5.16 and it started to crash. I tried to switch to pre-release version and it's not helping. It was all good before upgrading.

Not sure if this is the place to report... maybe it's related to my local setup.

### Reproduction steps
1. (Upgrade LSP v0.5.16)
2. open vscode and try to initialize the language server (ruby file opened)
3. Got the following error message:
```ruby
2024-03-29 16:42:41.408 [info] (easyship-api) Ruby LSP> Skipping custom bundle setup since /Users/johnhsu/easyship-api/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-03-29 16:42:41.426 [info] (easyship-api) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2024-03-29 16:42:41.877 [info] (easyship-api) The following gems are missing
 * yabeda-prometheus-mmap (0.3.0)
 * prometheus-client-mmap (0.16.2)
Install missing gems with `bundle install`

2024-03-29 16:42:43.106 [info] (easyship-api) Fetching gem metadata from https://gems.easyship.com/
2024-03-29 16:42:43.107 [info] (easyship-api) .
2024-03-29 16:42:43.476 [info] (easyship-api) .
2024-03-29 16:42:43.580 [info] (easyship-api) .
2024-03-29 16:42:43.626 [info] (easyship-api) .
2024-03-29 16:42:43.654 [info] (easyship-api) .
2024-03-29 16:42:43.658 [info] (easyship-api) .
2024-03-29 16:42:44.605 [info] (easyship-api) 

2024-03-29 16:42:44.719 [info] (easyship-api) Fetching gem metadata from https://gems.easyship.com/private/
2024-03-29 16:42:44.719 [info] (easyship-api) .
2024-03-29 16:42:44.762 [info] (easyship-api) .
2024-03-29 16:42:44.800 [info] (easyship-api) .
2024-03-29 16:42:44.801 [info] (easyship-api) 

2024-03-29 16:42:44.967 [info] (easyship-api) Fetching gem metadata from https://gems.easyship.com/upstream/gems.contribsys.com/.
2024-03-29 16:42:44.969 [info] (easyship-api) .
2024-03-29 16:42:44.971 [info] (easyship-api) 

2024-03-29 16:42:45.194 [info] (easyship-api) Installing prometheus-client-mmap 0.16.2 with native extensions

2024-03-29 16:42:46.294 [info] (easyship-api) Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/johnhsu/.gem/ruby/3.2.0/gems/prometheus-client-mmap-0.16.2/ext/fast_mmaped_file
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/bin/ruby extconf.rb
creating Makefile

current directory:
/Users/johnhsu/.gem/ruby/3.2.0/gems/prometheus-client-mmap-0.16.2/ext/fast_mmaped_file
make DESTDIR\= sitearchdir\=./.gem.20240329-26108-81kh63
sitelibdir\=./.gem.20240329-26108-81kh63 clean

current directory:
/Users/johnhsu/.gem/ruby/3.2.0/gems/prometheus-client-mmap-0.16.2/ext/fast_mmaped_file
make DESTDIR\= sitearchdir\=./.gem.20240329-26108-81kh63
sitelibdir\=./.gem.20240329-26108-81kh63
compiling fast_mmaped_file.c
In file included from fast_mmaped_file.c:4:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:28:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic.h:24:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic/char.h:29:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/core/rstring.h:30:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:788:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTABLE(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:805:26:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED_RAW(VALUE obj)
                         ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:822:22:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED(VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:837:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT_RAW(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:852:20:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT(VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:25:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                        ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:36:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:21:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                    ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:32:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                               ^
In file included from fast_mmaped_file.c:4:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:45:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:22:
warning: unused parameter 'clone' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:35:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                                  ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:20:
warning: unused parameter 'dup' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:31:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                              ^
13 warnings generated.
compiling file_format.c
compiling file_parsing.c
In file included from file_parsing.c:1:
In file included from ./file_parsing.h:3:
In file included from ./file_reading.h:3:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:28:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic.h:24:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic/char.h:29:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/core/rstring.h:30:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:788:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTABLE(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:805:26:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED_RAW(VALUE obj)
                         ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:822:22:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED(VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:837:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT_RAW(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:852:20:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT(VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:25:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                        ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:36:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:21:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                    ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:32:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                               ^
In file included from file_parsing.c:1:
In file included from ./file_parsing.h:3:
In file included from ./file_reading.h:3:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:45:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:22:
warning: unused parameter 'clone' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:35:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                                  ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:20:
warning: unused parameter 'dup' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:31:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                              ^
13 warnings generated.
compiling file_reading.c
In file included from file_reading.c:1:
In file included from ./file_reading.h:3:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:28:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arith
2024-03-29 16:42:46.294 [info] (easyship-api) metic.h:24:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic/char.h:29:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/core/rstring.h:30:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:788:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTABLE(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:805:26:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED_RAW(VALUE obj)
                         ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:822:22:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED(VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:837:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT_RAW(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:852:20:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT(VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:25:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                        ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:36:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:21:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                    ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:32:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                               ^
In file included from file_reading.c:1:
In file included from ./file_reading.h:3:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:45:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:22:
warning: unused parameter 'clone' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:35:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                                  ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:20:
warning: unused parameter 'dup' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:31:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                              ^
13 warnings generated.
compiling hashmap.c
compiling jsmn.c
compiling mmap.c
In file included from mmap.c:1:
In file included from ./mmap.h:4:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:28:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic.h:24:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/arithmetic/char.h:29:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/core/rstring.h:30:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:788:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTABLE(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:805:26:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED_RAW(VALUE obj)
                         ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:822:22:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINTED(VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:837:24:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT_RAW(VALUE obj)
                       ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:852:20:
warning: unused parameter 'obj' [-Wunused-parameter]
RB_OBJ_TAINT(VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:25:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                        ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:868:36:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
                                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:21:
warning: unused parameter 'dst' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                    ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/fl_type.h:884:32:
warning: unused parameter 'src' [-Wunused-parameter]
RB_OBJ_INFECT(VALUE dst, VALUE src)
                               ^
In file included from mmap.c:1:
In file included from ./mmap.h:4:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby.h:38:
In file included from
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/ruby.h:45:
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:22:
warning: unused parameter 'clone' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                     ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:173:35:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_clone_setup(VALUE clone, VALUE obj)
                                  ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:20:
warning: unused parameter 'dup' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                   ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/newobj.h:190:31:
warning: unused parameter 'obj' [-Wunused-parameter]
rb_dup_setup(VALUE dup, VALUE obj)
                              ^
mmap.c:27:5: warning: 'rb_gc_force_recycle' is deprecated: this is now a no-op
function [-Wdeprecated-declarations]
    rb_gc_force_recycle(str);
    ^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/intern/gc.h:213:1:
note: 'rb_gc_force_recycle' has been explicitly marked deprecated here
RBIMPL_ATTR_DEPRECATED(("this is now a no-op function"))
^
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/attr/deprecated.h:36:53:
note: expanded from macro 'RBIMPL_ATTR_DEPRECATED'
# define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
                                                    ^
mmap.c:80:25: error: incompatible function pointer types passing 'VALUE (VALUE
*)' (aka 'unsigned long (unsigned long *)') to parameter of type 'VALUE
(*)(VALUE)' (aka 'unsigned long (*)(unsigned long)')
[-Wincompatible-function-pointer-types]
        res = rb_ensure(mm_protect_bang, (VALUE)tmp, mm_recycle, str);
                        ^~~~~~~~~~~~~~~
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/include/ruby-3.2.0/ruby/internal/iterator.h:425:25:
note: passing argument to parameter 'b_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE),
VALUE data2);
                        ^
mmap.c:68:14: warning: a function definition without a prototype is deprecated
in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
static VALUE mm_i_bang(bang_st) mm_bang *bang_st;
             ^
mmap.c:184:5: warning: '__li
2024-03-29 16:42:46.294 [info] (easyship-api) nux__' is not defined, evaluates to 0 [-Wundef]
#if __linux__
    ^
16 warnings and 1 error generated.
make: *** [mmap.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/johnhsu/.gem/ruby/3.2.0/gems/prometheus-client-mmap-0.16.2 for
inspection.
Results logged to
/Users/johnhsu/.gem/ruby/3.2.0/extensions/arm64-darwin-23/3.2.0/prometheus-client-mmap-0.16.2/gem_make.out

/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in
`run'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:53:in
`block in make'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in
`each'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in
`make'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in
`build'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in
`build_extension'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in
`block in build_extensions'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in
`each'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in
`build_extensions'
/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/installer.rb:846:in
`build_extensions'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:205:in
`install'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in
`install'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in
`apply_func'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in
`block in process_queue'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`loop'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`process_queue'
/Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing prometheus-client-mmap (0.16.2), and Bundler
cannot continue.

In Gemfile:
  yabeda-prometheus-mmap was resolved to 0.3.0, which depends on
    prometheus-client-mmap

2024-03-29 16:42:46.811 [info] (easyship-api) /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:596:in `materialize': Could not find yabeda-prometheus-mmap-0.3.0, prometheus-client-mmap-0.16.2 in locally installed gems (Bundler::GemNotFound)
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:203:in `specs'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:270:in `specs_for'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:18:in `setup'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler.rb:162:in `setup'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `block in <top (required)>'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:159:in `with_level'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:111:in `silence'
	from /Users/johnhsu/.gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `<top (required)>'
	from <internal:/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/johnhsu/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

2024-03-29 16:42:46.814 [info] (easyship-api) [Error - 4:42:46 PM] Server process exited with code 1.
2024-03-29 16:42:46.815 [info] (easyship-api) [Error - 4:42:46 PM] Server initialization failed.
2024-03-29 16:42:46.815 [info] (easyship-api)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-03-29 16:42:46.816 [info] (easyship-api) [Error - 4:42:46 PM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-03-29 16:42:46.816 [info] (easyship-api) [Error - 4:42:46 PM] Ruby LSP client: couldn't create connection to server.
2024-03-29 16:42:46.816 [info] (easyship-api)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-03-29 16:42:46.816 [info] (easyship-api) [Error - 4:42:46 PM] Restarting server failed
2024-03-29 16:42:46.816 [info] (easyship-api)   Message: Pending response rejected since connection got disposed
  Code: -32097 
```
Not sure how I can install  * yabeda-prometheus-mmap (0.3.0) and * prometheus-client-mmap (0.16.2) properly.

I had another issue in the beginning where ruby: warning: Ruby was built without YJIT support. You may need to install rustc to build Ruby with YJIT. But it was resolved by installing rustc and reinstall ruby.

Any thought would be helpful. Thank you very much.

**Comment by cyhsujohn** [comment]
solved with `bundle update`

**Comment by vinistock** [comment]
Hello! Thank you for the report.

We recently re-worked RVM activation so it's likely we broke something. While we work to fix this, downgrading to the previous version should make it work.

I have a few questions to understand the problem. It seems that a native extension is failing to compile when running bundle install.

1. I assume that running bundle install in your terminal installs that gem successfully. Is that correct?
2. Do you have any bundle related configuration in your shell configuration files (e.g.: `~/.zshrc`, `~/.bashrc`)? Anything that tells bundler where to look for specific libraries?

**Comment by cyhsujohn** [comment]
Hi! Thank you for looking into this.
For the questions you asked:
> 1. I assume that running bundle install in your terminal installs that gem successfully. Is that correct?

Yes. Running bundle install in my terminal is fine.

> 2. Do you have any bundle related configuration in your shell configuration files (e.g.: ~/.zshrc, ~/.bashrc)? Anything that tells bundler where to look for specific libraries?

I have:
```
# ~/.bashrc

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
. "$HOME/.cargo/env"
```

```
# ~/.zshrc

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
```
Not sure if these are related.
