### ISSUE TITLE
LSP is looking for missing gem but gem is already installed.

### ISSUE THREAD

**Issue by lightweightcoder** [Shopify/ruby-lsp#1863]
### Description
I opened a ruby file, rubyLSP tries to start -> looks for missing gems and realises that mysql2 (0.5.3) is missing so it tries to install it but fails at installation step. This happened only today and I did not update the gem. I think LSP is looking at a different folder for the gem.

### Expected Behaviour
- rubyLSP should be able to find the gem so it does not need to install it.

### System / Project specs
- Ruby LSP VS Code extension: v0.5.16. 
- Using rvm 1.29.12 to manage my ruby version.
- `bundle --version` shows 2.3.7
- `ruby --version` shows 3.1.1p18
- `echo $GEM_HOME` shows /Users/aljt/.rvm/gems/ruby-3.1.1
-  `echo $GEM_PATH` shows /Users/aljt/.rvm/gems/ruby-3.1.1:/Users/aljt/.rvm/gems/ruby-3.1.1@global
- `echo $RUBY_VERSION` shows ruby-3.1.1
- `ruby -e 'puts [Gem.user_dir, Gem.default_dir]'` shows 
    /Users/aljt/.gem/ruby/3.1.0
    /Users/aljt/.rvm/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0
- `bundle info mysql2` shows the path is `/Users/aljt/.rvm/gems/ruby-3.1.1/gems/mysql2-0.5.3`

### VScode output logs from LSP
The GEM_HOME and GEM_PATH variables are different from the ones I ran in the terminal using `echo`
```bash
Activated Ruby environment: GEM_HOME=/Users/aljt/.gem/ruby/3.1.0 GEM_PATH=/Users/aljt/.gem/ruby/3.1.0:/Users/aljt/.rvm/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0 PATH=/Users/aljt/.gem/ruby/3.1.0/bin:/Users/aljt/.rvm/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0/bin:/Users/aljt/.rvm/rubies/ruby-3.1.1/bin:/Users/aljt/.rvm/gems/ruby-3.1.1/bin:/Users/aljt/.rvm/gems/ruby-3.1.1@global/bin:/Users/aljt/.rvm/rubies/ruby-3.1.1/bin:/Users/aljt/.nvm/versions/node/v12.20.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/aljt/.rvm/bin

...some logs...

The following gems are missing
 * mysql2 (0.5.3)
Install missing gems with `bundle install`

...some logs...

An error occurred while installing mysql2 (0.5.3), and Bundler cannot continue.
In Gemfile:
  mysql2

/Users/aljt/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/bundler/definition.rb:481:in `materialize': Could not find mysql2-0.5.3 in any of the sources (Bundler::GemNotFound)

... more logs...
```

#### Troubleshooting
- Tried to uninstall the extension, deleted the `.ruby-lsp` folder and reinstalled but did not work.

**Comment by rafasoares** [comment]
I'm seeing the same issue, but with `iconv`. 

Running `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle install` from the project root succeeds (but the LSP still doesn't work).

I've tried forcing the version manager to RVM, no change.

I rolled back to `v0.5.15` and it works.

**Comment by lightweightcoder** [comment]
@vinistock Yup it works now. Thank you for fixing it quickly! 🚀

**Comment by dgmora** [comment]
I've noticed a similar error, but when using [`mise`](https://github.com/jdx/mise) (before called `rtx`, is similar to `asdf`.

`BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle install` works correctly, however when starting the server I get:

```
[ERROR][2024-05-22 07:30:33] .../vim/lsp/rpc.lua:752    "rpc"   "/Users/david/.local/share/nvim/mason/bin/ruby-lsp"        "stderr"        "Resolving dependencies...\n"
[ERROR][2024-05-22 07:30:33] .../vim/lsp/rpc.lua:752    "rpc"   "/Users/david/.local/share/nvim/mason/bin/ruby-lsp"        "stderr"        "Installing prism 0.27.0 with native extensions\n"
[ERROR][2024-05-22 07:30:40] .../vim/lsp/rpc.lua:752    "rpc"   "/Users/david/.local/share/nvim/mason/bin/ruby-lsp"        "stderr"        "Bundle complete! 6 Gemfile dependencies, 39 gems now installed.\n"
[ERROR][2024-05-22 07:30:40] .../vim/lsp/rpc.lua:752    "rpc"   "/Users/david/.local/share/nvim/mason/bin/ruby-lsp"        "stderr"        "Use `bundle info [gemname]` to see where a bundled gem is installed.\n"
[ERROR][2024-05-22 07:30:41] .../vim/lsp/rpc.lua:752    "rpc"   "/Users/david/.local/share/nvim/mason/bin/ruby-lsp"        "stderr"        "/Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/definition.rb:601:in `materialize': Could not find standard-1.36.0, rspec-mocks-3.13.1, rubocop-1.63.5, standard-performance-1.4.0, sorbet-runtime-0.5.11385, parser-3.3.1.0, regexp_parser-2.9.2, rexml-3.2.8, rubocop-ast-1.31.3, rubocop-performance-1.21.0, racc-1.8.0, strscan-3.1.0 in cached gems or installed locally (Bundler::GemNotFound)
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/definition.rb:207:in `specs'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/definition.rb:273:in `specs_for'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:18:in `setup'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler.rb:163:in `setup'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/setup.rb:29:in `block in <top (required)>'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/ui/shell.rb:159:in `with_level'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/ui/shell.rb:111:in `silence'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/bundler/setup.rb:29:in `<top (required)>'
from <internal:/Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
from <internal:/Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
from /Users/david/.local/share/mise/installs/ruby/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems.rb:1382:in `<top (required)>'
from <internal:gem_prelude>:2:in `require'
from <internal:gem_prelude>:2:in `<internal:gem_prelude>'\n"
```

This is in the context of a gem, using `standard`. Should I open a new issue, or is it the same thing?

**Comment by rafasoares** [comment]
Sorry @vinistock, I missed the notification from this thread. 
I'm on 0.5.21 and I have no issues at the moment :)
