### ISSUE TITLE
Ruby LSP client: couldn't create connection to server.

### ISSUE THREAD

**Issue by vol1ura** [Shopify/ruby-lsp#1866]
### Description

I have last version of vsc and ruby-lsp gem. When I start vsc I get next output:

```
2024-04-02 16:25:09.039 [info] (proj) Activated Ruby environment: GEM_HOME=/Users/vol1ura/.gem/ruby/3.2.0 GEM_PATH=/Users/vol1ura/.gem/ruby/3.2.0:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0 PATH=/Users/vol1ura/.gem/ruby/3.2.0/bin:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/bin:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/bin:/Users/vol1ura/.rvm/gems/ruby-3.2.2/bin:/Users/vol1ura/.rvm/gems/ruby-3.2.2@global/bin:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/bin:/Users/vol1ura/.rvm/bin:/opt/homebrew/opt/libpq/bin:/Users/vol1ura/.nvm/versions/node/v12.22.11/bin:/Users/vol1ura/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
2024-04-02 16:25:09.353 [info] (proj) /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/definition.rb:524:in `materialize': Could not find debug-1.9.2, erb_lint-0.5.0, rubocop-1.62.1, rubocop-performance-1.21.0, rubocop-rails-2.24.1, rubocop-rake-0.6.0, rubocop-rspec-2.28.0, ruby-lsp-0.14.6, ruby-lsp-rspec-0.1.10, solargraph-0.50.0, irb-1.12.0, reline-0.5.0, activesupport-7.1.3.2, better_html-2.1.1, parser-3.3.0.5, rainbow-3.1.1, smart_properties-1.17.0, json-2.7.1, language_server-protocol-3.17.0.3, parallel-1.24.0, regexp_parser-2.9.0, rexml-3.2.6, rubocop-ast-1.31.2, ruby-progressbar-1.13.0, unicode-display_width-2.5.0, rack-3.0.10, rubocop-capybara-2.20.0, rubocop-factory_bot-2.25.1, rubocop-rspec_rails-2.28.2, prism-0.24.0, sorbet-runtime-0.5.11323, backport-1.2.0, benchmark-0.3.0, diff-lcs-1.5.1, e2mmap-0.1.0, jaro_winkler-1.5.6, kramdown-2.4.0, kramdown-parser-gfm-1.1.0, rbs-2.8.4, reverse_markdown-2.1.1, thor-1.3.1, tilt-2.3.0, yard-0.9.36, rdoc-6.6.3.1, io-console-0.7.2, base64-0.2.0, bigdecimal-3.1.7, concurrent-ruby-1.2.3, connection_pool-2.4.1, drb-2.2.1, i18n-1.14.4, minitest-5.22.3, mutex_m-0.2.0, tzinfo-2.0.6, actionview-7.1.3.2, ast-2.4.2, erubi-1.12.0, racc-1.7.3, nokogiri-1.16.3-arm64-darwin, psych-5.1.2, builder-3.2.4, rails-dom-testing-2.2.0, rails-html-sanitizer-1.6.0, stringio-3.1.0, loofah-2.22.0, crass-1.0.6 in locally installed gems (Bundler::GemNotFound)
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/definition.rb:197:in `specs'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/definition.rb:254:in `specs_for'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:18:in `setup'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler.rb:171:in `setup'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
	from <internal:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/vol1ura/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

2024-04-02 16:25:09.354 [info] (proj) [Error - 16:25:09] Server process exited with code 1.
2024-04-02 16:25:09.355 [info] (proj) [Error - 16:25:09] Server initialization failed.
2024-04-02 16:25:09.355 [info] (proj)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-04-02 16:25:09.355 [info] (proj) [Info  - 16:25:09] Connection to server got closed. Server will restart.
2024-04-02 16:25:09.355 [info] (proj) true
2024-04-02 16:25:09.355 [info] (proj) [Error - 16:25:09] Ruby LSP client: couldn't create connection to server.
2024-04-02 16:25:09.355 [info] (proj)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-04-02 16:25:09.355 [error] (proj) Error starting the server: Pending response rejected since connection got disposed
```

In extension settings I point to Gemfile for LSP:

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem "debug", ">= 1.0.0"
gem 'erb_lint'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'ruby-lsp'
gem "ruby-lsp-rspec", require: false
gem 'solargraph'
```

**Comment by vinistock** [comment]
We just release https://github.com/Shopify/ruby-lsp/releases/tag/vscode-ruby-lsp-v0.5.17, with some RVM fixes. Can you please give it a try and let us know if the issue has been fixed?
