### ISSUE TITLE
bundler: failed to load command: ruby-lsp (rbenv)

### ISSUE THREAD

**Issue by jalaj-hn** [Shopify/ruby-lsp#2114]
### Reproduction steps

1. Start the Ruby LSP using a certain editor
2. Open a Ruby file
3. Errors start popping up
<img width="517" alt="image" src="https://github.com/Shopify/ruby-lsp/assets/146080512/715e8dff-b3fd-4105-8fbc-154e6600a421">

**Code snippet or error message**
```ruby
2024-05-31 12:37:41.491 [info] (project_name) [Error - 12:37:41] Restarting server failed
2024-05-31 12:37:41.492 [info] (project_name)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-31 12:37:41.550 [info] (project_name) ruby: warning: Ruby was built without YJIT support. You may need to install rustc to build Ruby with YJIT.

2024-05-31 12:37:41.923 [info] (project_name) bundler: failed to load command: ruby-lsp (/Users/myusername/.rbenv/versions/3.2.2/bin/ruby-lsp)

2024-05-31 12:37:41.923 [info] (project_name) /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/definition.rb:524:in `materialize': Could not find rubocop-1.57.2, rubocop-rails-2.22.1, ruby-lsp-0.12.1, solargraph-0.49.0, parser-3.2.2.4, regexp_parser-2.8.2, rexml-3.2.6, rubocop-ast-1.30.0, unicode-display_width-2.5.0, activesupport-7.1.1, rack-3.0.8, prism-0.15.1, sorbet-runtime-0.5.11105, rbs-2.8.4, thor-1.3.0, tilt-2.3.0, bigdecimal-3.1.4, connection_pool-2.4.1, minitest-5.20.0, nokogiri-1.15.4-arm64-darwin in locally installed gems (Bundler::GemNotFound)
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/definition.rb:197:in `specs'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/definition.rb:254:in `specs_for'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:18:in `setup'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler.rb:171:in `setup'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:56:in `require_relative'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:56:in `kernel_load'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/myusername/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /Users/myusername/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/myusername/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

2024-05-31 12:37:41.924 [info] (project_name) [Error - 12:37:41] Server initialization failed.
2024-05-31 12:37:41.924 [info] (project_name)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-31 12:37:41.924 [info] (project_name) [Error - 12:37:41] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-05-31 12:37:41.924 [info] (project_name) [Error - 12:37:41] Ruby LSP client: couldn't create connection to server.
2024-05-31 12:37:41.924 [info] (project_name)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-31 12:37:41.924 [info] (project_name) [Error - 12:37:41] Restarting server failed
2024-05-31 12:37:41.924 [info] (project_name)   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-05-31 12:37:41.925 [info] (project_name) [Error - 12:37:41] Server process exited with code 1.

```

**Comment by andyw8** [comment]
@jalaj-hn Does the project you're opening have a `Gemfile`?

**Comment by modosc** [comment]
this _just_ started happening for me today as well - was a new update pushed out recently?

**Comment by andyw8** [comment]
@modosc which version manager are you using?

**Comment by modosc** [comment]
> @modosc which version manager are you using?

rbenv

**Comment by andyw8** [comment]
This may relate to https://github.com/Shopify/ruby-lsp/pull/1966

**Comment by andyw8** [comment]
Can each of you share what's in your path, i.e.:

```
echo $PATH
```

**Comment by modosc** [comment]
```
/opt/homebrew/opt/libpq/bin:/opt/homebrew/opt/go@1.16/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/sbin:/Users/jon/git/chrome-passwords-cli:/Users/jon/.rbenv/shims:/Users/jon/.nvm/versions/node/v18.18.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/munki:/Users/jon/Library/Android/sdk/emulator:/Users/jon/Library/Android/sdk/platform-tools
```

**Comment by andyw8** [comment]
Just reformatting:

```
/opt/homebrew/opt/libpq/bin:
/opt/homebrew/opt/go@1.16/bin:
/Library/Frameworks/Python.framework/Versions/2.7/bin:
/usr/local/sbin:
/Users/jon/git/chrome-passwords-cli:
/Users/jon/.rbenv/shims:
/Users/jon/.nvm/versions/node/v18.18.2/bin:
/opt/homebrew/bin:
/opt/homebrew/sbin:
/usr/local/bin:
/System/Cryptexes/App/usr/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:
/Library/Apple/usr/bin:
/usr/local/munki:
/Users/jon/Library/Android/sdk/emulator:
/Users/jon/Library/Android/sdk/platform-tools
```

**Comment by Earlopain** [comment]
I've seen something similar happen when ruby-lsp did something funky during gem installation (previous bug):

By default gems get installed somewhere in `~/rbenv` but ruby-lsp put them in `~/.local/share/gems` (`Gem.user_dir`). This in turn confused everything and I had to manually delete that folder for things to start working again.

I don't think this will be the solution here but the error looks similar enough to what I encountered that I though I'd mention it.

**Comment by modosc** [comment]
> A few questions to help diagnose:
> 
> 1. Do you have any `rbenv` customizations? Not counting `.ruby-version` files. I'm looking for stuff like overriding `GEM_HOME` or `GEM_PATH`, pointing `rbenv` to some non-default location or anything configured in shell scripts

i use a single `rbenv` plugin ([rbenv-bundler](https://github.com/modosc/rbenv-bundler)) - i tried removing this and it makes no difference.

> 2. Do you have any Bundler configurations? Setting `BUNDLE_PATH` or any non-defaults?
```
Settings are listed in order of priority. The top value will be used.
build.pg
Set for your local app (/Users/jon/git/repo-name/.bundle/config): "--with-pg-config=/opt/homebrew/opt/libpq/bin/pg_config"

cache_all
Set for your local app (/Users/jon/git/repo-name/.bundle/config): false

enterprise.contribsys.com
Set for the current user (/Users/jon/.bundle/config): "[REDACTED]:[REDACTED]"

gem.changelog
Set for the current user (/Users/jon/.bundle/config): false

gem.ci
Set for the current user (/Users/jon/.bundle/config): false

gem.coc
Set for the current user (/Users/jon/.bundle/config): false

gem.linter
Set for the current user (/Users/jon/.bundle/config): false

gem.mit
Set for the current user (/Users/jon/.bundle/config): false

gem.test
Set for the current user (/Users/jon/.bundle/config): false

rubygems.pkg.github.com
Set for the current user (/Users/jon/.bundle/config): "[REDACTED]"
```

> 3. Similarly, any Rubygems configuration? A `~/.gemrc` file configuring different install locations?

there's a `~/.gem/credentials` file that matches the value in `~/.bundle/config` but otherwise nothing.

> 4. If you run the activation script manually in your terminals, what values (if any) are printed for GEM_HOME, GEM_PATH and PATH?

i do not run this manually, it's from vscode so i'm not 100% sure what to check here.
when i go into the `.ruby-lsp` inside of my repo:

```
work ~/git/repo/.ruby-lsp $ echo $GEM_PATH

work ~/git/repo/.ruby-lsp $ echo $GEM_HOME

work ~/git/repo/.ruby-lsp$ ruby-lsp
-bash: ruby-lsp: command not found

work ~/git/repo/.ruby-lsp $ gem which ruby-lsp
/Users/jon/.gem/ruby/3.3.0/gems/ruby-lsp-0.17.1/lib/ruby-lsp.rb

work ~/git/repo/.ruby-lsp $ /Users/jon/.gem/ruby/3.3.0/gems/ruby-lsp-0.17.1/exe/ruby-lsp
Ruby LSP> Skipping custom bundle setup since LSP dependencies are already in /Users/jon/git/horizon-api/.ruby-lsp/Gemfile
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: command not found: ruby-lsp
Install missing gem executables with `bundle install`
```
 > If you run the activation script manually in your terminals, what values (if any) are printed for GEM_HOME, GEM_PATH and PATH?

from that script there are no `GEM*` env values. there are some `RBENV`-specific values:
```
"RBENV_HOOK_PATH":"/Users/jon/.rbenv/rbenv.d:/opt/homebrew/Cellar/rbenv/1.2.0/rbenv.d:/opt/homebrew/etc/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"

"RBENV_ORIG_PATH":"/opt/homebrew/opt/libpq/bin:/opt/homebrew/opt/go@1.16/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/sbin:/Users/jon/git/chrome-passwords-cli:/Users/jon/.rbenv/shims:/Users/jon/.nvm/versions/node/v18.18.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/munki:/Users/jon/Library/Android/sdk/emulator:/Users/jon/Library/Android/sdk/platform-tools"
```
and the rest:
```
"yjit":false,"version":"3.3.1
```

**Comment by jalaj-hn** [comment]
@vinistock 

> 1. Do you have any `rbenv` customizations? Not counting `.ruby-version` files. I'm looking for stuff like overriding `GEM_HOME` or `GEM_PATH`, pointing `rbenv` to some non-default location or anything configured in shell scripts

No

> 2. Do you have any Bundler configurations? Setting `BUNDLE_PATH` or any non-defaults?

No
> 3. Similarly, any Rubygems configuration? A `~/.gemrc` file configuring different install locations?

No
> 4. If you run the activation script manually in your terminals, what values (if any) are printed for GEM_HOME, GEM_PATH and PATH?

```json
{
  "env": {
    "RBENV_VERSION": "3.2.2",
    "RBENV_ROOT": "/Users/username/.rbenv",
    "RBENV_HOOK_PATH": "/Users/username/.rbenv/rbenv.d:/opt/homebrew/Cellar/rbenv/1.2.0/rbenv.d:/opt/homebrew/etc/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks",
    "PATH": "/Users/username/.rbenv/versions/3.2.2/bin:/opt/homebrew/Cellar/rbenv/1.2.0/libexec:/Users/username/.cargo/bin:/Users/username/.nvm/versions/node/v16.13.2/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/username/.cargo/bin:/Users/username/Library/Android/sdk/emulator:/Users/username/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home",
    "RUBY_CONFIGURE_OPTS": "--with-openssl-dir=/opt/homebrew/opt/openssl@1.1",
    "RBENV_ORIG_PATH": "/Users/username/.cargo/bin:/Users/username/.nvm/versions/node/v16.13.2/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/username/.cargo/bin:/Users/username/Library/Android/sdk/emulator:/Users/username/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home",
    "RBENV_SHELL": "zsh",
    "RBENV_DIR": "/Users/username/projects/work/project_name",
    "RUBYLIB": "/opt/homebrew/Cellar/rbenv/1.2.0/rbenv.d/exec/gem-rehash:"
  },
  "yjit": true,
  "version": "3.2.2"
}
```

**Comment by Earlopain** [comment]
> Oh, I wasn't aware of that. I tried searching for GEM_HOME inside rbenv and couldn't find anywhere where it gets overridden.

`GEM_HOME` is indeed not set, it is falling back to `Gem.default_dir`. You can confirm this here: https://github.com/rubygems/rubygems/blob/8434a2d87bab605795466fd9d38b5c474cf307aa/lib/rubygems/path_support.rb#L27-L28

That implementation doesn't look quite like I imagined it would, but it makes sense how it would infer that path without any help: https://github.com/rubygems/rubygems/blob/8434a2d87bab605795466fd9d38b5c474cf307aa/lib/rubygems/defaults.rb#L38-L39

```sh
irb(main):010> Gem.dir
=> "/home/user/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0"
irb(main):011> Gem.default_dir
=> "/home/user/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0"
irb(main):012> RbConfig::CONFIG["rubylibprefix"]
=> "/home/user/.rbenv/versions/3.3.1/lib/ruby"
```

**Comment by Earlopain** [comment]
Try renaming that folder so something else temporarily and see if ruby-lsp starts working again. I suspect it may after restarting vscode

**Comment by Earlopain** [comment]
And just to confirm, `.local/share/gem` doesn't exist?

**Comment by modosc** [comment]
so i got this working locally but i'm unsure exactly which steps resolved this. going to list them all just in case because i don't want to try and intentionally break my setup again.
1. from the root of my repo i ran `gem install ruby-lsp`
2. i re-ran `rbenv rehash` to ensure the `ruby-lsp` shim(s) were created:
```
work ~/git/repo $ which ruby-lsp
/Users/jon/.rbenv/shims/ruby-lsp
```
3. i tried running `ruby-lsp` from my repo root and got some errors (note the `https://enterprise.contribsys.com` references - i'm unsure why we're trying to locate packages in that repo? we do have a `source` block for it in our `Gemfile`)
```
work ~/git/repo $ ruby-lsp
Ruby LSP> Skipping custom bundle setup since /Users/jon/git/repo/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: ((bundle check && bundle update ruby-lsp ruby-lsp-rails) || bundle install) 1>&2
The Gemfile's dependencies are satisfied
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Could not find compatible versions

Because ruby-lsp-rails < 0.3.7 depends on sorbet-runtime >= 0.5.9897
  and sorbet-runtime >= 0.5.9897, < 0.5.10782 could not be found in rubygems repository https://enterprise.contribsys.com/,
  ruby-lsp-rails < 0.3.7 requires sorbet-runtime >= 0.5.10782.
And because ruby-lsp-rails >= 0.3.7 depends on ruby-lsp >= 0.17.0, < 0.18.0,
  either sorbet-runtime >= 0.5.10782 or ruby-lsp >= 0.17.0, < 0.18.0.
So, because ruby-lsp >= 0.13.4 depends on sorbet-runtime >= 0.5.10782
  and sorbet-runtime >= 0.5.10782 could not be found in rubygems repository https://enterprise.contribsys.com/,
  version solving has failed.
Bundle complete! 82 Gemfile dependencies, 231 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
```
after all the above the `ruby-lsp` server seemed to start - i killed it in the terminal then moved to the `.ruby-lsp` directory
6. at this point running `ruby-lsp` works - everything in `vscode` functions as it should and i can run it manually from the `.ruby-lsp` directory.

**Comment by jalaj-hn** [comment]
> I just made a [preview release for v0.7.3](https://github.com/Shopify/ruby-lsp/releases/tag/vscode-ruby-lsp-v0.7.3) with the changes in #2133.
> 
> If someone is willing to install the prerelease and give it a try, please let me know if it fixes the issue.

Hi, I tried the preview release and its working now.
