### ISSUE TITLE
ruby-lsp-0.17.4/lib/ruby_lsp/store.rb:44:in `binread': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by chiperific** [Shopify/ruby-lsp#2219]
### Reproduction steps

VS Code: Version: 1.90.2 (Universal)
Ruby: ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
Ruby LSP: ✗ ruby-lsp (0.17.4)

**Code snippet or error message**
```sh
2024-06-21 10:06:17.778 [info] (obp-api) [Error - 10:06:17 AM] Server process exited with code 1.
2024-06-21 10:06:17.779 [info] (obp-api) [Info  - 10:06:17 AM] Connection to server got closed. Server will restart.
2024-06-21 10:06:17.779 [info] (obp-api) true
2024-06-21 10:06:17.973 [info] (obp-api) Ruby LSP> Skipping lockfile copies because there's no top level bundle

2024-06-21 10:06:17.990 [info] (obp-api) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2024-06-21 10:06:18.105 [info] (obp-api) The Gemfile's dependencies are satisfied

2024-06-21 10:06:18.471 [info] (obp-api) Initializing Ruby LSP v0.17.4...

2024-06-21 10:06:18.486 [info] (obp-api) Finished initializing Ruby LSP!

2024-06-21 10:06:18.641 [info] (obp-api) /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/store.rb:44:in `binread': no implicit conversion of nil into String (TypeError)

      set(uri: uri, source: File.binread(path), version: 0)
                                         ^^^^
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/store.rb:44:in `get'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/base_server.rb:55:in `block (2 levels) in start'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/base_server.rb:46:in `synchronize'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/base_server.rb:46:in `block in start'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/lib/ruby_lsp/base_server.rb:39:in `start'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/sorbet-runtime-0.5.11439/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/sorbet-runtime-0.5.11439/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/gems/ruby-lsp-0.17.4/exe/ruby-lsp:110:in `<top (required)>'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/bin/ruby-lsp:25:in `load'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/bin/ruby-lsp:25:in `<main>'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/bin/ruby_executable_hooks:22:in `eval'
	from /Users/chipkragt/.rvm/gems/ruby-3.3.1/bin/ruby_executable_hooks:22:in `<main>'

2024-06-21 10:06:18.647 [info] (obp-api) [Error - 10:06:18 AM] Server process exited with code 1.
2024-06-21 10:06:18.647 [info] (obp-api) [Error - 10:06:18 AM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by chiperific** [comment]
After rebooting my laptop, I can no longer replicate the error.
