### ISSUE TITLE
uninitialized constant SyntaxTree::BraceBlock

### ISSUE THREAD

**Issue by tvdeyen** [Shopify/ruby-lsp#2346]
### Reproduction steps

1. Start the Ruby LSP using VSCode
2. Open a Ruby file
3. Wait until the Ruby LSP server launches
4. Open Output Panel

**This error message appears**
```ruby
2024-07-23 18:01:21.656 [info] (<Project>) [Info  - 18:01:21] Connection to server got closed. Server will restart.
2024-07-23 18:01:21.658 [info] (<Project>) false
2024-07-23 18:01:21.989 [info] (<Project>) Ruby LSP> Skipping custom bundle setup since /Users/tvd/code/<client>/<project>/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-07-23 18:01:22.004 [info] (<Project>) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2024-07-23 18:01:22.268 [info] (<Project>) The Gemfile's dependencies are satisfied

2024-07-23 18:01:22.827 [info] (<Project>) Starting Ruby LSP...

2024-07-23 18:01:24.516 [info] (<Project>) bundler: failed to load command: ruby-lsp (/Users/tvd/.gem/ruby/3.3.3/bin/ruby-lsp)

2024-07-23 18:01:24.518 [info] (<Project>) /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/requests/folding_ranges.rb:17:in `<class:FoldingRanges>': uninitialized constant SyntaxTree::BraceBlock (NameError)

        SyntaxTree::BraceBlock,
                  ^^^^^^^^^^^^
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/requests/folding_ranges.rb:14:in `<module:Requests>'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/requests/folding_ranges.rb:4:in `<module:RubyLsp>'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/requests/folding_ranges.rb:3:in `<top (required)>'
	from /Users/tvd/.rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/tvd/.rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:106:in `block in respond_with_folding_ranges'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/document.rb:25:in `cache_fetch'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/store.rb:40:in `cache_fetch'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:105:in `respond_with_folding_ranges'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/cli.rb:50:in `block (2 levels) in start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:45:in `handle'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:30:in `block (2 levels) in start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:161:in `with_telemetry'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:30:in `block in start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/handler.rb:29:in `start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/lib/ruby_lsp/cli.rb:78:in `start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/ruby-lsp-0.0.3/exe/ruby-lsp:8:in `<top (required)>'
	from /Users/tvd/.gem/ruby/3.3.3/bin/ruby-lsp:25:in `load'
	from /Users/tvd/.gem/ruby/3.3.3/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli.rb:455:in `exec'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli.rb:35:in `dispatch'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/cli.rb:29:in `start'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/exe/bundle:28:in `block in <top (required)>'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/tvd/.gem/ruby/3.3.3/gems/bundler-2.5.13/exe/bundle:20:in `<top (required)>'
	from /Users/tvd/.gem/ruby/3.3.3/bin/bundle:25:in `load'
	from /Users/tvd/.gem/ruby/3.3.3/bin/bundle:25:in `<main>'

2024-07-23 18:01:24.524 [info] (<Project>) [Error - 18:01:24] Server process exited with code 1.
```

**Comment by andyw8** [comment]
@tvdeyen The logs indicate a very old version of `ruby-lsp` from more than 2 years ago. The extension attempts to use the latest version, so it's likely that something in your bundle is constraining it.

To help troubleshoot, can you try temporarily add the latest version in your `Gemfile` (v0.17.8) and run `bundle`?

**Comment by andyw8** [comment]
(please re-open if you need further assistance)

**Comment by vinistock** [comment]
You're still running on the extremely old v0.0.3

```
2024-07-23 18:18:26.794 [info] (<Project>) Note: ruby-lsp version regressed from 0.17.8 to 0.0.3
Bundle updated!
```

As Andy mentioned, something in your bundle is locking the `ruby-lsp` gem to a super old version.

If you have the `ruby-lsp` in your Gemfile, remove it and reload the VS Code window.

If you don't, try to update the gem and check why that's failing.

```shell
BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle update ruby-lsp
```

If that command does not upgrade it to v0.17.8, then the project may be constraining one of the Ruby LSP's runtime dependencies, which are

- rbs
- sorbet-runtime
- prism

**Comment by tvdeyen** [comment]
@vinistock that actually worked 🎉 

```
› BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle update ruby-lsp
Fetching gem metadata from https://gems.contribsys.com/..
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Resolving dependencies...
Using ruby-lsp 0.17.8 (was 0.0.3)
Bundle updated!
```

Since I do not have `ruby-lsp` in my `Gemfile` and none of the above mentioned gems I am not sure it's an issue on my end. I just installed the extension since it was released and kept it up to date since. 🤷🏻 

My guess is Ruby 3.3.3 (that has issues with installing correct gems, no?)

**Comment by vinistock** [comment]
There's no detriment to removing the `.ruby-lsp` directory. It will just be re-generated from scratch and re-composing the bundle from a clean state probably fixed the issue.
