### ISSUE TITLE
Client fails with default Lazyvim config

### ISSUE THREAD

**Issue by ogirginc** [Shopify/ruby-lsp#2347]
### Description

According to docs, there shouldn't be a need for any configuration when [Lazyvim](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#lazyvim-lsp) is used. However, that's not the case for me.

### Reproduction steps

1. Open Neovim.
2. Open any Ruby file.
3. ruby-lsp will fail.
```
Client ruby_lsp quit with exit code 1 and signal 0. Check log for errors: /Users/ogirginc/.local/state/nvim/lsp. log
```

**Error message**

```ruby
[ERROR][2024-07-23 21:42:35] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/ogirginc/.local/share/nvim/mason/bin/ruby-lsp"	"stderr"	"/Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': linked to incompatible /Users/ogirginc/.asdf/installs/ruby/3.3.0/lib/libruby.3.3.dylib - /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism/prism.bundle (LoadError)\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism.rb:78:in `<top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/lib/ruby_lsp/internal.rb:19:in `<top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/exe/ruby-lsp:82:in `<top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `load'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `<top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `load'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `kernel_load'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:23:in `run'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:455:in `exec'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:35:in `dispatch'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:29:in `start'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:28:in `block in <top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:20:in `<top (required)>'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `load'\n\tfrom /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `<main>'\n"
```

**Versions**
```
ruby -v #=>ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
ruby-lsp -v #=> 0.17.8
nvim -v #=> NVIM v0.10.0
lazyvim #=> [12.36.0](https://github.com/LazyVim/LazyVim/compare/v12.35.1...v12.36.0) (2024-07-22)

```

**Comment by andyw8** [comment]
Just reformatting for easier reading:

```
[ERROR][2024-07-23 21:42:35] .../vim/lsp/rpc.lua:770 "rpc" "/Users/ogirginc/.local/share/nvim/mason/bin/ruby-lsp" "stderr" "/Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': linked to incompatible /Users/ogirginc/.asdf/installs/ruby/3.3.0/lib/libruby.3.3.dylib - /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism/prism.bundle (LoadError)
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism.rb:78:in `<top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/lib/ruby_lsp/internal.rb:19:in `<top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/exe/ruby-lsp:82:in `<top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `load'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `<top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `load'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:23:in `run'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:455:in `exec'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:35:in `dispatch'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:29:in `start'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:28:in `block in <top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:20:in `<top (required)>'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `load'
    from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `<main>'\n"
```

**Comment by andyw8** [comment]
@ogirginc could you verify that `gem install prism` succeeds?

**Comment by ogirginc** [comment]
Just did a 

```
> gem install prism
Building native extensions. This could take a while...
Successfully installed prism-0.30.0
Parsing documentation for prism-0.30.0
Done installing documentation for prism after 1 seconds
1 gem installed
```

and follow the steps, bug got the error below:

```
[ERROR][2024-07-23 22:09:21] .../vim/lsp/rpc.lua:770 "rpc" "/Users/ogirginc/.local/share/nvim/mason/bin/ruby-lsp" "stderr"
"/Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': linked to incompatible /Users/ogirginc/.asdf/installs/ruby/3.3.0/lib/libruby.3.3.dylib
 - /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism/prism.bundle (LoadError)
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
   from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/prism-0.30.0/lib/prism.rb:78:in `<top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
   from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/lib/ruby_lsp/internal.rb:19:in `<top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
   from /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/gems/ruby-lsp-0.17.8/exe/ruby-lsp:82:in `<top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `load'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/ruby-lsp:25:in `<top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `load'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli/exec.rb:23:in `run'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:455:in `exec'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:35:in `dispatch'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/cli.rb:29:in `start'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:28:in `block in <top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:20:in `<top (required)>'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `load'
   from /Users/ogirginc/.asdf/installs/ruby/3.3.4/bin/bundle:25:in `<main>'\n"
```

**Comment by andyw8** [comment]
Thanks. This seem to relate to your Ruby installation. Could you try `gem uninstall prism`, then try Ruby LSP again?

**Comment by vinistock** [comment]
Are you launching the Ruby LSP using ASDF's shim for selecting the correct Ruby version? This is documented in the important note for all editors https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#editors.

**Comment by ogirginc** [comment]
> Are you launching the Ruby LSP using ASDF's shim for selecting the correct Ruby version? This is documented in the important note for all editors [`main`/EDITORS.md#editors](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md?rgh-link-date=2024-07-24T13%3A55%3A40Z#editors).

I am not sure if I understood the setup process, but before opening this ticket, I have tried some things that I couldn't remember. However, here is what did after your comment:

1. Checked the `:LspInfo`

<img width="900" alt="Screenshot 2024-07-24 at 21 08 01" src="https://github.com/user-attachments/assets/10fb940e-fc9e-4e78-a9da-eed743282152">

2. Inspect `/Users/ogirginc/.local/share/nvim/mason/bin/ruby-lsp`

```bash
#!/usr/bin/env bash
export GEM_PATH="/Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp:$GEM_PATH"
exec /Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp/bin/ruby-lsp "$@"
```

3. It looked odd, so I have tried configuring `"neovim/nvim-lspconfig"`:

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      diagnostics = {
        underline = false,
        virtual_text = false,
      },
      servers = {
        ruby_ls = {
          -- cmd = { "asdf", "exec", "ruby-lsp" },
          cmd = { "~/.asdf/shims/ruby-lsp" },
          filetypes = { "ruby" },
          root_dir = require("lspconfig.util").root_pattern("Gemfile", ".git"),
        },
      },
    },
  },
}
```

4. Both `cmd = { "asdf", "exec", "ruby-lsp" }` and `cmd = { "~/.asdf/shims/ruby-lsp" }` did not change the outcome on `:LspInfo`

5. As a last resort, I have updated the file like this, but again it did not change the outcome on `:LspInfo`

```bash
#!/usr/bin/env bash
export GEM_PATH="/Users/ogirginc/.local/share/nvim/mason/packages/ruby-lsp:$GEM_PATH"
exec /Users/ogirginc/.asdf/shims/ruby-lsp "$@"
```

**Comment by adipasquale** [comment]
Thank you for this useful thread! I’m just learning LazyVim and had a hard time getting `ruby-lsp` to work. I had to slightly tweak the suggested config by wrapping the `servers` in an `opts` key : 


```lua
-- ~/.config/nvim/lua/plugins/nvim-lspconfig.lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      ruby_lsp = {
        mason = false,
        cmd = { vim.fn.expand("~/.rbenv/shims/ruby-lsp") },
      },
    },
  },
}
```

Maybe I should be storing this lua config file in another place ? Thanks anyways!
