### ISSUE TITLE
Language server not starting.

### ISSUE THREAD

**Issue by bhanuone** [Shopify/ruby-lsp#2519]
### Description

The extension used to work fine until it stopped working suddenly. The language server is unable to start because of some bundler issue.
```ruby
bundler: failed to load command: ruby-lsp (/Users/user292/.asdf/installs/ruby/3.3.0/bin/ruby-lsp
```

> Error stack

```
/Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile?  (Gem::Exception)
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/user292/.asdf/installs/ruby/3.3.0/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/user292/workspace/project/.ruby-lsp/vendor/ruby/3.3.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /Users/user292/.asdf/installs/ruby/3.3.0/bin/bundle:25:in `load'
	from /Users/user292/.asdf/installs/ruby/3.3.0/bin/bundle:25:in `<main>'
```

#### VS Code Version

1.92.2

#### Ruby LSP Extension Version

0.7.18

#### Ruby LSP Server Version

0.17.17

#### Ruby Version

3.3.0

#### Ruby Version Manager

asdf

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- markdown-mermaid (1.23.1)
- copilot (1.224.0)
- copilot-chat (0.18.2)
- go (0.42.0)
- vscode-docker (1.29.2)
- debugpy (2024.10.0)
- python (2024.12.3)
- vscode-pylance (2024.8.2)
- remote-containers (0.380.0)
- vscode-speech (0.10.0)
- ruby-lsp (0.7.18)
- haml (1.0.1)
- vim (1.28.0)
- gitblame (11.0.1)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{
  "indexing": {
    "excludedPatterns": [
      "spec/**/*"
    ],
    "excludedGems": [
      "rubocop",
      "rubocop-performance"
    ]
  }
}
```

##### User

```json
{
  "enableExperimentalFeatures": true,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "rubyVersionManager": {
    "identifier": "asdf"
  },
  "customRubyCommand": "",
  "formatter": "auto",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {
    "excludedPatterns": [
      "spec/**/*"
    ],
    "excludedGems": [
      "rubocop",
      "rubocop-performance"
    ]
  },
  "erbSupport": true
}
```

</details>

**Comment by vinistock** [comment]
Thanks for the bug report. I suspect this is something related to the `BUNDLE_PATH` configuration based on the fact that the backtrace is including `/.../workspace/project/.ruby-lsp/vendor`.

You shouldn't be getting a `vendor` directory under the custom bundle directory (`.ruby-lsp`), so something is definitely not right.

What is `BUNDLE_PATH` configured to? And are those project or user configs (`~/.bundle/config` or `/path/to/your/project/.bundle/config`)?

**Comment by vinistock** [comment]
You shouldn't need to copy the `.bundle` directory inside `.ruby-lsp`. We should be inheriting the project configs here https://github.com/Shopify/ruby-lsp/blob/bacd882d11e055787a26daa18853370370598b13/lib/ruby_lsp/setup_bundler.rb#L194

Does it not work if you remove the `.ruby-lsp/.bundle` directory completely?

**Comment by vinistock** [comment]
Okay, so it might be a bug in our debug client. Does the language server work if you delete the `.ruby-lsp/vendor` directory? Do you get go to definition, formatting, etc?

**Comment by bhanuone** [comment]
> Does the language server work if you delete the .ruby-lsp/vendor directory? Do you get go to definition, formatting, etc?

Yes, everything works fine after deleting the .ruby-lsp/vendor directory. However, whenever I close and open the project, the extension again installs the gems into the vendor directory during initialization. It's annoying every time I have to delete this folder to get it working.
