### ISSUE TITLE
Error during indexing: "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#2674]
### Ruby LSP Information

<details><summary>Details</summary>
<p>

#### VS Code Version

1.94.0

#### Ruby LSP Extension Version

0.8.2

#### Ruby LSP Server Version

0.19.1

#### Ruby Version

3.3.5

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- gitlens (15.5.1)
- go (0.42.1)
- vscode-rdbg (0.2.2)
- remote-containers (0.388.0)
- material-icon-theme (5.11.1)
- vscode-yaml (1.15.0)
- ruby-lsp (0.8.2)
- sorbet-vscode-extension (0.3.37)
- vscode-wakatime (24.6.2)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "none",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true
}
```

</details>

</p>
</details> 

### Reproduction steps

From `ruby/spec`

```rb
# -*- encoding: binary -*-
require_relative '../../spec_helper'
require_relative 'fixtures/classes'

describe "IO#readpartial" do
  it "reads after ungetc with multibyte characters in the buffer" do
    @wr.write("∂φ/∂x = gaîté")
    c = @rd.getc
    @rd.ungetc(c)
    @rd.readpartial(3).should == "\xE2\x88\x82"
    @rd.readpartial(3).should == "\xCF\x86/"
  end
end
```

Backtrace looks something like this:
```
 Error processing textDocument/definition: /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.1.0/lib/prism/parse_result.rb:93:in `encode': "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.1.0/lib/prism/parse_result.rb:93:in `code_units_offset'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.1.0/lib/prism/parse_result.rb:278:in `end_code_units_offset'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/ruby_document.rb:66:in `locate'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/requests/definition.rb:41:in `initialize'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11597/lib/types/private/abstract/declare.rb:37:in `new'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11597/lib/types/private/abstract/declare.rb:37:in `block in declare_abstract'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/server.rb:913:in `text_document_definition'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/server.rb:69:in `process_message'
	from /home/earlopain/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/base_server.rb:154:in `block in new_worker'
```

**Comment by vinistock** [comment]
This should prevent the failures on files that use binary encoding with multibyte characters https://github.com/ruby/prism/pull/3168.

**Comment by vlasar** [comment]
@vinistock Apologies if this is inappropriate, but I’m seeing the following in my LSP log in Neovim and really miss having a working Ruby LSP:

```
[ERROR][2024-10-22 16:46:15] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/vlasar/.rbenv/shims/ruby-lsp"	"stderr"	"/Users/vlasar/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/writer.rb:16:in 'to_json': \"\\xE2\" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)\n\tfrom /Users/vlasar/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/writer.rb:16:in 'write'\n\tfrom /Users/vlasar/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.1/lib/ruby_lsp/base_server.rb:27:in 'block (2 levels) in initialize'\n\tfrom /Users/vlasar/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.1/lib/ruby_lsp/base_server.rb:27:in 'synchronize'\n\tfrom /Users/vlasar/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.1/lib/ruby_lsp/base_server.rb:27:in 'block in initialize'\n"
```

I have been using Ruby LSP in Neovim for a good while now and this started happening recently. Not sure if it is the same issue as the OP and where to go from here.

**Comment by vinistock** [comment]
@vlasar that issue might be related, but it's not exactly the same. Could you please open a separate issue?

Please include these so that we can diagnose what's going wrong:

1. When does that error happen? For example, does it happen when you open a file? When you type something? When you hover over something?
2. Do you have the full stack trace for the error (and not just the last frame)?
3. Based on the error, it says some content was encoded in `ASCII-8BIT` and we tried to convert it to UTF-8. I have questions related to this:
    - Are your files encoded in `ASCII-8BIT`? If it's not all of them, does this only happen in the ones encoded with it?
    - Is your terminal encoding set to `ASCII-8BIT` instead of `UTF-8`?
    - When you see the error, does it happen on files with multibyte characters such as emoji or Japanese characters? Or do you see the error even in files using only ASCII characters?
