### ISSUE TITLE
FormattingExtension 'Ruby LSP' is configured as formatter but it cannot format 'Ruby'-files

### ISSUE THREAD

**Issue by Skoti** [Shopify/ruby-lsp#2692]
#### VS Code Version

1.93.1

#### Ruby LSP Extension Version

0.8.3

#### Ruby LSP Server Version

0.19.1

#### Ruby Version

3.3.2

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- circleci (2.8.4)
- doxdocgen (1.4.0)
- githistory (0.6.20)
- bats (0.1.10)
- Kotlin (1.7.1)
- vscode-docker (1.29.3)
- vscode-dotnet-runtime (2.1.7)
- debugpy (2024.10.0)
- python (2024.14.1)
- vscode-pylance (2024.10.1)
- remote-containers (0.388.0)
- remote-ssh (0.115.0)
- remote-ssh-edit (0.87.0)
- remote-wsl (0.88.4)
- cmake-tools (1.19.52)
- cpptools (1.21.6)
- cpptools-extension-pack (1.3.0)
- cpptools-themes (2.0.0)
- remote-explorer (0.4.3)
- vscode-pbkit (0.0.8)
- platformio-ide (3.3.3)
- vscode-yaml (1.15.0)
- ruby-lsp (0.8.3)
- code-spell-checker (3.0.1)
- io (3.19.0)
- cmake (0.0.17)
- vscode-lldb (1.11.0)
- vscode-gradle (3.16.4)
- grammarly (0.24.0)
- vscode-proto3 (0.5.5)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{
  "formatter": "rubocop"
}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "rbenv"
  },
  "customRubyCommand": "",
  "formatter": "rubocop",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true
}
```

</details>

### Reproduction steps

1. Open VSCode
2. Open a Ruby file
3. Initializing Ruby LSP
4. Ruby LSP: Indexing files
5. It gets interrupted due to `Server process exited with code 0.` (see below)
6. Go to point `3` - infinite loop ❗ 

**Code snippet or error message**

VSCode Output:
```
Ruby LSP> Skipping custom bundle setup since {redacted}/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
Initializing Ruby LSP v0.19.1...
Using formatter specified by user: rubocop
Auto detected linters: rubocop
Detected test library: rspec
Finished initializing Ruby LSP!
Running command: `rbenv exec ruby -W0 -rjson -e 'STDERR.print("RUBY_LSP_ACTIVATION_SEPARATOR" + { env: ENV.to_h, yjit: !!defined?(RubyVM:: YJIT), version: RUBY_VERSION }.to_json + "RUBY_LSP_ACTIVATION_SEPARATOR")'` in {redacted} using shell: /bin/zsh
Server process exited with code 0.
```
The extension status switches between these two:

![Image](https://github.com/user-attachments/assets/2a44cf6c-7e6f-4e7b-b63e-adf5ba30a3f4)

![Image](https://github.com/user-attachments/assets/c7380f4a-4889-452b-9abb-2500ee4b60b3)

**Comment by Skoti** [comment]
I do have `rubocop` in Gemfile.

After running in the loop for ~20 min I got this Output:
```
{redacted}/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/exe/ruby-lsp:66:in `exec': Argument list too long - bundle (Errno::E2BIG)
	from {redacted}/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/exe/ruby-lsp:66:in `<top (required)>'
	from {redacted}/.rbenv/versions/3.3.2/bin/ruby-lsp:25:in `load'
	from {redacted}/.rbenv/versions/3.3.2/bin/ruby-lsp:25:in `<main>'

Server initialization failed.
Message: Pending response rejected since connection got disposed
  Code: -32097 
Ruby LSP client: couldn't create connection to server.
Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting the server: Pending response rejected since connection got disposed
Server process exited with code 1.
Error restarting the server: Client is not running and can't be stopped. It's current state is: startFailed
```

and then after retrying to start from the VSCode prompt, I got:
```
Connection to server got closed. Server will restart.
false
Restarting server failed
Error: Client got disposed and can't be restarted.
	at ms.start ({redacted}/.vscode/extensions/shopify.ruby-lsp-0.8.3/out/extension.js:41:1845)
	at ms.handleConnectionClosed ({redacted}/.vscode/extensions/shopify.ruby-lsp-0.8.3/out/extension.js:41:13479)
```

**Comment by Skoti** [comment]
yes it is `zsh`

**Comment by andyw8** [comment]
@Skoti which Bundler version is in `Gemfile.lock`? We suspect this a problem with a specific Bundler version that we previously encountered. You can try update your repo with `bundle update --bundler`.

**Comment by andyw8** [comment]
Can you try running `rm -rf .ruby-lsp` then `ruby-lsp --doctor`, and see if it fails in the same way.

**Comment by Skoti** [comment]
`original_args: []` 😸

**Comment by Skoti** [comment]
hmm, it's the same path 🤔

**Comment by Skoti** [comment]
no, it only contains `BUNDLE_GEMFILE`

**Comment by Skoti** [comment]
the issue is not arguments but the fact that `ruby-lsp` runs in an infinite loop, and the reason for that is this condition:
`if ENV["BUNDLE_GEMFILE"].nil?`
as the value is always `nil`

**Comment by vinistock** [comment]
I don't understand how. On [this line](https://github.com/Shopify/ruby-lsp/blob/5ec5b4b76ffe96365ae8b0b12bdbd8763fb0c5f4/exe/ruby-lsp#L72), we replace the current process (`ruby-lsp`) with `bundle exec ruby-lsp`, which should have `BUNDLE_GEMFILE` properly set.

Maybe this is related to Bundler auto-restarts due to version mismatches (#2532)? Can you please confirm if this still happens on the version released today v0.20.1?

**Comment by Skoti** [comment]
it's still the same issue

**Comment by vinistock** [comment]
Are you hitting #2711 by any chance? Do you have a mismatch between the locked Ruby version and the one defined in the Gemfile?

We need to figure out what's triggering the restarts. I think it might either be Bundler restarting or something is touching `Gemfile.lock` and triggering our restart watcher non stop.

If you simply boot the LSP manually, does this loop happen?

```shell
# Launching the LSP should only print after setting up the bundle and then
# it will hang waiting for an initialize request. If it properly reaches that
# stage, then the loop doesn't happen when launching the LSP manually
# You can CTRL + C to exit
ruby-lsp
```

**Comment by vinistock** [comment]
If launching the server manually doesn't cause the restart loop, then I believe it's coming from our [restart watchers](https://github.com/Shopify/ruby-lsp/blob/bb336e5d0a4639ca2381d6a8658fd875896635bd/vscode/src/workspace.ts#L332).

For example, there was a [Bundler bug a while back](https://github.com/Shopify/ruby-lsp/issues/2183) that kept touching `Gemfile.lock` even when no modifications were made, which meant that it fired our restart watcher and caused the LSP to keep restarting.

I created #2736 to add some extra logging for us to better understand what's happening. I suspect something is continuously triggering our restarts.

**Comment by andyw8** [comment]
Does your project have a `.rubocop.yml` at the root?

**Comment by vinistock** [comment]
Do you have something that would be repeatedly updating a `.rubocop.yml` inside the workspace? Maybe another VS Code extension or some sort of background process?

We need to restart the language server when the RuboCop configs are changed so that they are reflected in linting and auto formatting.

**Comment by vinistock** [comment]
In [v0.8.8](https://github.com/Shopify/ruby-lsp/releases/tag/vscode-ruby-lsp-v0.8.8), we added a check to only restart if the contents of the watched files have changed.

It's still not clear to me what in your setup continuously touches the `.rubocop.yml` despite not making any modifications, but the change should avoid the repeated restarts.

Please let us know if this is not the case.
