### ISSUE TITLE
Stack level too deep while fetching references

### ISSUE THREAD

**Issue by gregolsen** [Shopify/ruby-lsp#2702]
#### VS Code Version

1.94.1

#### Ruby LSP Extension Version

0.8.4

#### Ruby LSP Server Version

0.19.1

#### Ruby LSP Addons

- Ruby LSP Rails

#### Ruby Version

3.3.4

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- ruby-lsp (0.8.4)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{
  "bypassTypechecker": true
}
```

##### User

```json
{
  "enableExperimentalFeatures": true,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "rbenv"
  },
  "customRubyCommand": "",
  "formatter": "rubocop",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": true,
  "rubyExecutablePath": "",
  "indexing": {
    "excludedPatterns": [
      "**/aws-sdk-**/**.rb"
    ]
  },
  "erbSupport": true
}
```

</details>

### Reproduction steps
"Go to references" results in a crash.
I added `warn(name)` in the beginning of the `follow_aliased_namespace` method and the output is this:

```
...
ReportingService::MetricService::Metrics::Articles::Constants::EVENTS_SOURCE
ReportingService::MetricService::Metrics::Articles::Constants::EVENTS_SOURCE
ReportingService::MetricService::Metrics::Articles::Constants::EVENTS_SOURCE
ReportingService::MetricService::Metrics::Articles::Constants::EVENTS_SOURCE

2024-10-10 15:38:22.646 [info] (intercom) #<Thread:0x000000012c3f8b08 /Users/inokentiimykhailov/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_lsp/base_server.rb:141 run> terminated with exception (report_on_exception is true):

2024-10-10 15:38:22.648 [info] (intercom) /Users/inokentiimykhailov/src/intercom/Gemfile:19:in `warn': stack level too deep (SystemStackError)
	from <internal:warning>:51:in `warn'
	from /Users/inokentiimykhailov/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_indexer/lib/ruby_indexer/index.rb:438:in `block in follow_aliased_namespace'
	from /Users/inokentiimykhailov/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_indexer/lib/ruby_indexer/index.rb:431:in `downto'
	from /Users/inokentiimykhailov/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_indexer/lib/ruby_indexer/index.rb:431:in `follow_aliased_namespace'
	from /Users/inokentiimykhailov/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.19.1/lib/ruby_indexer/lib/ruby_indexer/index.rb:439:in `block in follow_aliased_namespace'
```

**Simplified code snippet**
```ruby
module ReportingService
  module MetricService
    class Metrics
      module Articles

        Constants = ReportingService::MetricService::Metrics::Constants

        METRICS = [
          {
            source: Constants::EVENTS_SOURCE,
          }
        ].freeze

      end
    end
  end
end
```

**Comment by andyw8** [comment]
Thank you, I was able to reproduce when triggering Go To References on `EVENTS_SOURCE`.
