### ISSUE TITLE
Activating extension Shopify.ruby-lsp failed

### ISSUE THREAD

**Issue by HighwayStar** [Shopify/ruby-lsp#2725]
### Ruby LSP Information

Ruby LSP  v0.8.4

command for getting more info not working because Ruby LSP could not be started.

### Reproduction steps

Installed vs code version 
1.94.2
384ff7382de624fb94dbaf6da11977bba1ecd427
x64
on Fedora 40  from repo https://packages.microsoft.com/yumrepos/vscode

**Code snippet or error message**
```
2024-10-15 13:39:15.544 [info] Extension host with pid 26779 started
2024-10-15 13:39:15.544 [info] Skipping acquiring lock for /home/tomin/.config/Code/User/workspaceStorage/c3f5a831b4f04b4321d4a29a2332c19c.
2024-10-15 13:39:15.690 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-10-15 13:39:15.707 [info] ExtensionService#_doActivateExtension KoichiSasada.vscode-rdbg, startup: false, activationEvent: 'onLanguage:ruby'
2024-10-15 13:39:15.712 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onLanguage:ruby', root cause: Shopify.ruby-lsp
2024-10-15 13:39:15.855 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onLanguage:ruby', root cause: Shopify.ruby-lsp
2024-10-15 13:39:16.071 [info] ExtensionService#_doActivateExtension Shopify.ruby-lsp, startup: false, activationEvent: 'onLanguage:ruby'
2024-10-15 13:39:16.159 [info] ExtensionService#_doActivateExtension vscode.github, startup: false, activationEvent: '*'
2024-10-15 13:39:16.181 [info] ExtensionService#_doActivateExtension nick-rudenko.back-n-forth, startup: false, activationEvent: '*'
2024-10-15 13:39:16.266 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-10-15 13:39:16.328 [error] Activating extension Shopify.ruby-lsp failed due to an error:
2024-10-15 13:39:16.328 [error] TypeError: Cannot read properties of null (reading 'rootUri')
        at _a.activate (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:54:4611)
        at async Fa.activateWorkspace (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:175:2756)
        at async Fa.activate (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:175:1412)
        at async OS (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:177:266)
        at async x0.n (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4450)
        at async x0.m (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4413)
        at async x0.l (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:3869)
2024-10-15 13:39:16.350 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-10-15 13:39:16.451 [info] Eager extensions activated
2024-10-15 13:39:16.468 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 13:39:16.469 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 13:39:16.485 [info] ExtensionService#_doActivateExtension usernamehw.errorlens, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 13:39:21.476 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 13:39:21.484 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 13:39:21.497 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 14:13:23.896 [info] ExtensionService#_doActivateExtension vscode.debug-server-ready, startup: false, activationEvent: 'onDebugResolve'
2024-10-15 14:14:32.188 [info] Extension host terminating: renderer closed the MessagePort
2024-10-15 14:14:32.212 [error] Canceled: Canceled
        at new eA (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:109321)
        at Zb.U (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113933)
        at s.<computed>.n.charCodeAt.s.<computed> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111427)
        at T0.g (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32325)
        at T0.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
        at r.registerCommand.description (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31156)
        at T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32845)
        at T0.g (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31919)
        at T0.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
        at Object.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37049)
        at gh.O [as value] (/usr/share/code/resources/app/extensions/git/dist/main.js:2:953034)
        at T.B (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
        at T.C (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
        at T.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
        at Object.p [as dispose] (/usr/share/code/resources/app/extensions/git/dist/main.js:2:973612)
        at /usr/share/code/resources/app/extensions/git/dist/main.js:2:979734
        at Array.forEach (<anonymous>)
        at f.dispose (/usr/share/code/resources/app/extensions/git/dist/main.js:2:979720)
        at D1.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:19996)
        at D1.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:20092)
        at D1.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:955332)
        at D1.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:20092)
        at Si (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:701)
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14995
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1011
        at Object.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
        at hB.eb (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11922)
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9877
        at Array.map (<anonymous>)
        at hB.$ (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9865)
        at hB.terminate (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10108)
        at M3.terminate (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
        at ps (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15058)
        at MessagePortMain.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11603)
        at MessagePortMain.emit (node:events:519:28)
        at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) setContext undefined
2024-10-15 14:14:32.213 [error] Canceled: Canceled
        at new eA (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:109321)
        at Zb.U (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113933)
        at s.<computed>.n.charCodeAt.s.<computed> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111427)
        at T0.g (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32325)
        at T0.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
        at r.registerCommand.description (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31156)
        at T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32845)
        at T0.g (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31919)
        at T0.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
        at Object.executeCommand (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37049)
        at set hasGitHubRepositories (/usr/share/code/resources/app/extensions/github/dist/extension.js:2:321578)
        at /usr/share/code/resources/app/extensions/github/dist/extension.js:2:322537
        at gh.value (/usr/share/code/resources/app/extensions/git/dist/main.js:2:1061875)
        at T.B (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
        at T.C (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:802)
        at T.fire (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:1019)
        at Object.p [as dispose] (/usr/share/code/resources/app/extensions/git/dist/main.js:2:973612)
        at /usr/share/code/resources/app/extensions/git/dist/main.js:2:979734
        at Array.forEach (<anonymous>)
        at f.dispose (/usr/share/code/resources/app/extensions/git/dist/main.js:2:979720)
        at D1.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:19996)
        at D1.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:20092)
        at D1.<anonymous> (/usr/share/code/resources/app/extensions/git/dist/main.js:2:955332)
        at D1.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:20092)
        at Si (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:701)
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14995
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1011
        at Object.dispose (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
        at hB.eb (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11922)
        at file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9877
        at Array.map (<anonymous>)
        at hB.$ (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9865)
        at hB.terminate (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10108)
        at M3.terminate (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
        at ps (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15058)
        at MessagePortMain.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11603)
        at MessagePortMain.emit (node:events:519:28)
        at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) setContext undefined
2024-10-15 14:14:32.214 [info] Extension host with pid 26779 exiting with code 0
2024-10-15 14:14:32.651 [info] Extension host with pid 32846 started
2024-10-15 14:14:32.651 [info] Skipping acquiring lock for /home/tomin/.config/Code/User/workspaceStorage/c3f5a831b4f04b4321d4a29a2332c19c.
2024-10-15 14:14:32.660 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-10-15 14:14:32.672 [info] ExtensionService#_doActivateExtension KoichiSasada.vscode-rdbg, startup: false, activationEvent: 'onLanguage:ruby'
2024-10-15 14:14:32.675 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: '*', root cause: vscode.git
2024-10-15 14:14:32.677 [info] ExtensionService#_doActivateExtension nick-rudenko.back-n-forth, startup: false, activationEvent: '*'
2024-10-15 14:14:32.678 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-10-15 14:14:32.704 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 14:14:32.714 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 14:14:32.723 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 14:14:32.762 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2024-10-15 14:14:32.785 [info] ExtensionService#_doActivateExtension vscode.debug-server-ready, startup: false, activationEvent: 'onDebugResolve'
2024-10-15 14:14:32.818 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: '*'
2024-10-15 14:14:32.868 [info] ExtensionService#_doActivateExtension vscode.github, startup: false, activationEvent: '*'
2024-10-15 14:14:33.143 [info] Eager extensions activated
2024-10-15 14:14:33.145 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 14:14:33.146 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 14:14:33.158 [info] ExtensionService#_doActivateExtension usernamehw.errorlens, startup: false, activationEvent: 'onStartupFinished'
2024-10-15 14:14:35.880 [info] ExtensionService#_doActivateExtension Shopify.ruby-lsp, startup: false, activationEvent: 'onLanguage:ruby'
2024-10-15 14:14:35.946 [error] Activating extension Shopify.ruby-lsp failed due to an error:
2024-10-15 14:14:35.946 [error] TypeError: Cannot read properties of null (reading 'rootUri')
        at _a.activate (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:54:4611)
        at async Fa.activateWorkspace (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:175:2756)
        at async Fa.activate (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:175:1412)
        at async OS (/home/tomin/.vscode/extensions/shopify.ruby-lsp-0.8.4/out/extension.js:177:266)
        at async x0.n (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4450)
        at async x0.m (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4413)
        at async x0.l (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:3869)

```

**Comment by vinistock** [comment]
Thank you for the report! https://github.com/Shopify/ruby-lsp/pull/2727 will fix this.

**Comment by HighwayStar** [comment]
Thank you. Is there workaround to use current installed stable version? Do I have to just do git init in current project dir or I have also add remote? Because I've tried just init and had same issue.
