### ISSUE TITLE
The method `run_range_formatting` on RubyLsp::Requests::Support::Formatter is declared as `abstract`

### ISSUE THREAD

**Issue by danieldocki** [Shopify/ruby-lsp#2726]
### Description

1. I'm using VSCode
2. When open a Ruby file and editing this crash happen
3. I'm using standard for formatter and linters
4. Suspect that can be standard gem

**Code snippet or error message**
```ruby
#<Thread:0x000000015c8975f8 /Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.0/lib/ruby_lsp/base_server.rb:141 run> terminated with exception (report_on_exception is true):
/Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11602/lib/types/private/methods/call_validation.rb:23:in `block in wrap_method_if_needed': The method `run_range_formatting` on RubyLsp::Requests::Support::Formatter is declared as `abstract`. It does not have an implementation. (NotImplementedError)
	from /Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.0/lib/ruby_lsp/requests/range_formatting.rb:30:in `perform'
	from /Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.0/lib/ruby_lsp/server.rb:555:in `text_document_range_formatting'
	from /Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.0/lib/ruby_lsp/server.rb:47:in `process_message'
	from /Users/danieldocki/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.0/lib/ruby_lsp/base_server.rb:154:in `block in new_worker'
```

**Comment by vinistock** [comment]
Thank you for the report! This is due to the addition of range formatting to the LSP, but the Standard add-on doesn't support that yet.

The fix is to add the following declaration to [this class](https://github.com/standardrb/standard/blob/0c5a69fd43b3b2a5bf35278c261b53124b80fefd/lib/ruby_lsp/standard/wraps_built_in_lsp_standardizer.rb#L21).

```ruby
def run_range_formatting(uri, source, base_indentation)
  # Not yet supported. Should return the formatted version of `source` is a partial selection of the
  # entire document. For example, it should not try to add a frozen_string_literal magic comment and all
  # style corrections should start from the `base_indentation`
  nil
end
```
