### ISSUE TITLE
Crash on git gem in gemfile

### ISSUE THREAD

**Issue by thedanbob** [Shopify/ruby-lsp#2809]
#### VS Code Version

1.94.2

#### Ruby LSP Extension Version

0.8.12

#### Ruby LSP Server Version

Unknown

#### Ruby Version

3.3.5

#### Ruby Version Manager

custom

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- amx-netlinx (0.6.1)
- better-toml (0.3.2)
- copy-text (0.4.9)
- cpptools (1.22.10)
- csharp (2.50.27)
- elixir-ls (0.24.2)
- gitlens (15.6.2)
- go (0.42.1)
- haml (1.4.1)
- isort (2023.10.1)
- material-icon-theme (5.12.0)
- platformio-ide (3.3.3)
- postcss (2.0.0)
- python (2024.16.1)
- ruby-lsp (0.8.12)
- rust-analyzer (0.3.2162)
- vscode-dotnet-runtime (2.2.2)
- vscode-eslint (3.0.10)
- vscode-npm-script (0.3.29)
- vscode-projects-plus (1.24.0)
- vscode-zipfs (3.0.0)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "custom"
  },
  "customRubyCommand": "rbenv init - fish | source",
  "formatter": "auto",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true,
  "useLauncher": false
}
```

</details>

### Reproduction steps

Have a git gem in your gemfile with the following format:

`gem "gem_name", git: "git@git.example.com:username/repo.git", branch: "master"`

**Code snippet or error message (anonymized)**
```
2024-10-31 08:48:03.930 [info] (project) /home/dan/.rbenv/versions/3.3.5/lib/ruby/3.3.0/uri/rfc3986_parser.rb:130:in `split': bad URI(is not URI?): "git@git.example.com:username/repo.git" (URI::InvalidURIError)
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/3.3.0/uri/rfc3986_parser.rb:135:in `parse'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/3.3.0/uri/common.rb:187:in `parse'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/3.3.0/uri/common.rb:848:in `URI'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.0/lib/ruby_lsp/setup_bundler.rb:357:in `block in correct_relative_remote_paths'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.0/lib/ruby_lsp/setup_bundler.rb:352:in `gsub!'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.0/lib/ruby_lsp/setup_bundler.rb:352:in `correct_relative_remote_paths'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.0/lib/ruby_lsp/setup_bundler.rb:105:in `setup!'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dan/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.21.0/exe/ruby-lsp:75:in `<top (required)>'
	from /home/dan/.rbenv/versions/3.3/bin/ruby-lsp:25:in `load'
	from /home/dan/.rbenv/versions/3.3/bin/ruby-lsp:25:in `<main>'
```

This bug appears to have been introduced here: https://github.com/Shopify/ruby-lsp/commit/eadd4314fdee47ca1d5cfe88a14f220ba4f59977#diff-f6924adc23e6f34611ac67f8365789f93c0a71d7ccf25c626582755d85204eafR304

**Comment by vinistock** [comment]
Just cut [v0.21.1](https://github.com/Shopify/ruby-lsp/releases/tag/v0.21.1) with the fix. Please update the global installation of the gem so that you're using the version with the fix `gem update ruby-lsp`.
