### ISSUE TITLE
Ruby LSP in VSCode breaks rubocop

### ISSUE THREAD

**Issue by nduckwiler** [Shopify/ruby-lsp#2851]
#### VS Code Version

1.95.2

#### Ruby LSP Extension Version

0.8.13

#### Ruby LSP Server Version

0.21.3

#### Ruby LSP Addons

- Ruby LSP Rails

#### Ruby Version

3.3.1

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- angular-console (18.30.4)
- copilot (1.245.0)
- copilot-chat (0.22.2)
- csdevkit (1.13.9)
- csharp (2.55.29)
- debugpy (2024.12.0)
- gitlens (15.6.3)
- go (0.42.1)
- jupyter (2024.10.0)
- jupyter-keymap (1.1.2)
- jupyter-renderers (1.0.21)
- prettier-vscode (11.0.0)
- python (2024.20.0)
- ruby-lsp (0.8.13)
- vscode-dotnet-runtime (2.2.3)
- vscode-eslint (3.0.10)
- vscode-jest-runner (0.4.74)
- vscode-pylance (2024.11.2)
- vscodeintellicode-csharp (2.2.3)
- vstuc (1.0.4)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true,
    "references": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "auto",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true,
  "useLauncher": false,
  "featureFlags": {}
}
```

</details>

### Gem Env

<details>
<summary>Click to expand</summary>

### gem env

```
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.9
  - RUBY VERSION: 3.3.1 (2024-04-23 patchlevel 55) [arm64-darwin23]
  - INSTALLATION DIRECTORY: /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
  - USER INSTALLATION DIRECTORY: /Users/myuser/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/myuser/.rbenv/versions/3.3.1/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/myuser/.rbenv/versions/3.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/myuser/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/myuser/.rbenv/versions/3.3.1/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-23
  - GEM PATHS:
     - /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
     - /Users/myuser/.gem/ruby/3.3.0myuser
```
</details>

### Reproduction steps

1. Start the Ruby LSP with VSCode 
2. Get an error popup: "Error running diagnostics: An internal error occurred for the Layout/AssignmentIndentation cop. Updating to a newer version of RuboCop may solve this. For more details, run RuboCop on the command line."
3. In the root directory from which you opened VScode, run `rubocop -v`
4. Get this error message
```
/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:151:in `data': uninitialized constant Bundler::SharedHelpers (NameError)

      Bundler::SharedHelpers.filesystem_access(loaded_from, :read) do
             ^^^^^^^^^^^^^^^
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/stub_specification.rb:158:in `name'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/stub_specification.rb:88:in `activated?'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/specification.rb:1058:in `block in find_active_stub_by_path'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/specification.rb:1057:in `each'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/specification.rb:1057:in `find'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:86:in `block in require'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:211:in `<module:Gem>'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:33:in `<top (required)>'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `require_relative'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `<top (required)>'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop/lockfile.rb:6:in `<top (required)>'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop.rb:743:in `require_relative'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/lib/rubocop.rb:743:in `<top (required)>'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.5/exe/rubocop:15:in `<top (required)>'
	from /Users/myuser/.rbenv/versions/3.3.1/bin/rubocop:25:in `load'
	from /Users/myuser/.rbenv/versions/3.3.1/bin/rubocop:25:in `<main>'
```

I can get rubocop working again by running
```
> gem list psych

*** LOCAL GEMS ***

psych (5.2.0, default: 5.1.2)

> gem uninstall psych

Gem psych-5.1.2 cannot be uninstalled because it is a default gem
Successfully uninstalled psych-5.2.0

> rubocop -v

1.63.5
```

But when I reload my developer window (and thus restart Ruby LSP), psych 5.2.0 is re-installed and rubocop fails again

```
> gem list psych

*** LOCAL GEMS ***

psych (5.2.0, default: 5.1.2)

> rubocop -v
/Users/myuser/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:151:in `data': uninitialized constant Bundler::SharedHelpers (NameError)
```

Notes 
1. `bundle exec rubocop -v` still succeeds in my repo
2. When I disable Ruby LSP, then cleanup psych, then restart my VSCode window, psych 5.2.0 is not installed and rubcop -v works

**Comment by nduckwiler** [comment]
Seems like [upgrading to bundler 2.5.11 may fix the issue](https://github.com/rubocop/rubocop/issues/12891), however my shared repository is set to 2.5.10. Based on a [bundler issue](https://github.com/rubygems/rubygems/pull/7647) mentioned in that original link, it seems like I may have no choice but to upgrade bundler. Leaving open in case someone more knowledgeable has a better workaround

**Comment by nduckwiler** [comment]
Also I confirmed that my Ruby LSP extension is installing psych 5.2.0 by viewing the Output tab in VSCode
```
2024-11-15 12:09:59.521 [info] (progress_service_graphql) Ruby LSP> Skipping custom bundle setup since /Users/nickduckwiler/Repos/progress_service_graphql/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-11-15 12:09:59.703 [info] (progress_service_graphql) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: ((bundle _2.5.10_ check && bundle _2.5.10_ update ruby-lsp debug ruby-lsp-rails) || bundle _2.5.10_ install) 1>&2

2024-11-15 12:10:00.186 [info] (progress_service_graphql) The following gems are missing
 * psych (5.2.0)
Install missing gems with `bundle install`

2024-11-15 12:10:02.290 [info] (progress_service_graphql) Fetching gem metadata from https://rubygems.org/
2024-11-15 12:10:02.291 [info] (progress_service_graphql) .
2024-11-15 12:10:02.976 [info] (progress_service_graphql) .
2024-11-15 12:10:03.139 [info] (progress_service_graphql) .
2024-11-15 12:10:03.308 [info] (progress_service_graphql) .
2024-11-15 12:10:03.341 [info] (progress_service_graphql) .
2024-11-15 12:10:03.360 [info] (progress_service_graphql) .
2024-11-15 12:10:03.374 [info] (progress_service_graphql) .
2024-11-15 12:10:03.390 [info] (progress_service_graphql) .
2024-11-15 12:10:03.392 [info] (progress_service_graphql) .
2024-11-15 12:10:05.776 [info] (progress_service_graphql) 

2024-11-15 12:10:05.890 [info] (progress_service_graphql) Installing rake 13.2.1

2024-11-15 12:10:05.972 [info] (progress_service_graphql) Fetching psych 5.2.0

2024-11-15 12:10:07.886 [info] (progress_service_graphql) Installing psych 5.2.0 with native extensions

2024-11-15 12:10:09.051 [info] (progress_service_graphql) Bundle complete! 36 Gemfile dependencies, 148 gems now installed.
```

**Comment by nduckwiler** [comment]
Okay found a fix for my issue.
1. Stop Ruby LSP server
2. Cleanup gems

    ```console
    $ rm .ruby-lsp/Gemfile.lock
    $ gem uninstall psych
    Gem psych-5.1.2 cannot be uninstalled because it is a default gem
    Successfully uninstalled psych-5.2.0

    $ gem cleanup psych
    $ gem cleanup rubocop
    $ gem cleanup ruby-lsp-rails
    $ gem cleanup ruby-lsp
    ```
3. Restart Ruby LSP server

Now only psych 5.1.2 is installed
