### ISSUE TITLE
Will not start: Ruby LSP client: couldn't create connection to server.

### ISSUE THREAD

**Issue by brian-nicholls** [Shopify/ruby-lsp#879]
### Ruby version

3.2.2

### Description

I installed the VSC extension, and selected `rbenv` as my version manager. When trying to run Ruby LSP: Start from the command palette, I get the following output. VSC, Ruby, Bundler are all up to date. VSC is connected to a remote machine, and the extension is installed on the remote. Thanks for your help

Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Bundler attempted to update ruby-lsp but its version stayed the same
Bundler attempted to update debug but its version stayed the same
Bundle updated!
bundler: failed to load command: ruby-lsp (/home/developer/.rbenv/versions/3.2.2/bin/ruby-lsp)
/home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:540:in `materialize': Could not find <All of my gems listed here> in locally installed gems (Bundler::GemNotFound)
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:200:in `specs'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:266:in `specs_for'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:18:in `setup'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler.rb:162:in `setup'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:56:in `require_relative'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:56:in `kernel_load'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.18/exe/bundle:37:in `block in <top (required)>'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/developer/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.18/exe/bundle:29:in `<top (required)>'
	from /home/developer/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/developer/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:44:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:44:03 PM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 12:44:03 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:44:03 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

### Expected output

I expect it to run without errors, as the docs say all I need to do is install the extension.

**Comment by vinistock** [comment]
Thank you for the bug report! There seems to be some sort of mismatch between the time we run bundle install and boot the server. It successfully ran bundle install, but still didn't find the gems.

I'm not 100% sure, what's going on. Do you have any bundler configurations worth noting? E.g.: `BUNDLE_GEMFILE` or `BUNDLE_PATH`.

Do you get any different stack trace if you try to boot the LSP manually? You can do that by running `ruby-lsp` inside the folder for the project you're trying to use the LSP on.

There's a chance this might be the same problem as #738.

**Comment by brian-nicholls** [comment]
I get the same message when running `ruby-lsp` manually. I also tried removing the `.ruby-lsp` folder and re-installing the extension. I also made sure there were no old versions of it installed on my system. I also removed an old Ruby 2.7.0 folder in my `vendor` folder just in case.

There was a bundle config, so I removed it, and while it did get slightly farther (it installed Nokogiri) it then resulted in the same output.

Thanks again for your help!

**Comment by oliwoodsuk** [comment]
@brian-nicholls , I was getting a similar issue but have since added 'ruby-lsp' to my app's main Gemfile and that seems to have done the trick. (although I realise this isn't recommended as per the current gem readme)

**Comment by brian-nicholls** [comment]
> @brian-nicholls , I was getting a similar issue but have since added 'ruby-lsp' to my app's main Gemfile and that seems to have done the trick. (although I realise this isn't recommended as per the current gem readme)

Thanks, I tried this and got the same result unfortunately

**Comment by brian-nicholls** [comment]
Yes it is printing `vendor/bundle`. I forget how I was checking that before, but it wasn't through a Rails console, so I guess I was doing it wrong. Thanks for your help! I will keep an eye on the other issue.
