### ISSUE TITLE
ruby-lsp fails to start; symbol not found in flat namespace '_yp_encoding_utf_8'

### ISSUE THREAD

**Issue by dmlary** [Shopify/ruby-lsp#921]
### Ruby version

3.1.2

### Code snippet

`lsp-start`

### Description

on MacOS Ventura (13.4.1), with ruby-lsp v0.8.1.  On attempting to start `ruby-lsp`, I get the following error.  I've tried uninstalling & reinstalling both `ruby-lsp` & `yarp` gems with no change.

```txt
Ruby LSP> Skipping lockfile copies because there's no top level bundle
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 2.3.22
Using io-console 0.6.0
Using language_server-protocol 3.17.0.3
Using prettier_print 1.2.1
Using sorbet-runtime 0.5.10981
Using yarp 0.6.0
Using reline 0.3.8
Using syntax_tree 6.1.1
Using irb 1.7.4
Using debug 1.8.0
Using ruby-lsp 0.8.1
Bundler attempted to update ruby-lsp but its version stayed the same
Bundler attempted to update debug but its version stayed the same
Bundle updated!
bundler: failed to load command: ruby-lsp (/Users/dmlary/.rbenv/versions/3.1.2/bin/ruby-lsp)
/Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/lib/yarp.rb:330:in `require': dlopen(/Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/lib/yarp/yarp.bundle, 0x0009): symbol not found in flat namespace '_yp_encoding_utf_8' - /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/lib/yarp/yarp.bundle (LoadError)
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/lib/yarp.rb:330:in `<top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.1/lib/ruby_lsp/internal.rb:6:in `require'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.1/lib/ruby_lsp/internal.rb:6:in `<top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.1/exe/ruby-lsp:79:in `require_relative'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.8.1/exe/ruby-lsp:79:in `<top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/bin/ruby-lsp:25:in `load'
	from /Users/dmlary/.rbenv/versions/3.1.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /Users/dmlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
	from /Users/dmlary/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /Users/dmlary/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

### Expected output

ruby-lsp should start.

**Comment by andyw8** [comment]
Hi @dmlary, thanks for the report. I can't seem to reproduce when using 3.1.2. Would you mind trying on Ruby 3.2 and checking if you get the same result?

**Comment by dmlary** [comment]
> Also, how you are starting Ruby LSP, through the VS Code extension or some other way?

I was trying through neovim, but for this log, I'm just running `ruby-lsp` from the command-line.

> And please share the output of...

The symbol `_yp_encoding_utf_8` is undefined, so that's probably what's causing the error:
<details>
  <summary>
    `nm yarp.bundle` output
  </summary>
```txt
000000000000e1e4 ? 
000000000000d900 ? 
000000000000da94 ? 
000000000000e120 ? 
                 U 
000000000000da94 ? 
000000000000dce4 ? 
                 U 
                 U 
000000000000dce4 ? 
000000000000dcd8 ? 
                 U 
                 U 
000000000000d554 ? 
000000000000d660 ? 
                 U 
                 U 
000000000000d660 ? 
000000000000d7f4 ? 
000000000000dba0 ? 
                 U 
000000000000d7f4 ? 
000000000000d900 ? 
                 U 
                 U 
000000000000de50 ? 
000000000000e918 ? 
000000000000df90 ? 
                 U 
000000000000e918 ? 
000000000000dcd8 ? 
000000000000dccc ? 
                 U 
000000000000e120 ? 
000000000000e7f8 ? 
                 U 
000000000000e7f8 ? 
000000000000e6fc ? 
                 U 
000000000000e6fc ? 
000000000000dccc ? 
000000000000df90 ? 
                 U 
000000000000e600 ? 
                 U 
000000000000e600 ? 
000000000000e440 ? 
                 U 
000000000000e440 ? 
000000000000e3c8 ? 
                 U 
000000000000dcc0 ? 
                 U 
000000000000e3c8 ? 
0000000000003b1c ? 
000000000000e39c ? 
                 U 
0000000000003b1c ? 
0000000000003c14 ? 
                 U 
                 U 
0000000000003c14 ? 
0000000000003cdc ? 
                 U 
                 U 
0000000000003cdc ? 
000000000000b560 ? 
                 U 
000000000000b560 ? 
                 U 
000000000000e39c ? 
000000000000c180 ? 
                 U 
000000000000c180 ? 
000000000000c2b0 ? 
000000000000e1e4 ? 
                 U 
000000000000c2b0 ? 
000000000000e9d8 ? 
                 U 
                 U 
000000000000e9d8 ? 
000000000000de50 ? 
                 U 
000000000000dcc0 ? 
000000000000d0c4 ? 
                 U 
000000000000d0c4 ? 
000000000000d3c0 ? 
000000000000dba0 ? 
                 U 
000000000000d3c0 ? 
000000000000d554 ? 
                 U 
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/api_node.o
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/api_pack.o
                 U /Users/dlary/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/yarp-0.6.0/ext/yarp/extension.o
000000000000d0c4 T _Init_yarp
000000000000d0c4 ? _Init_yarp
000000000000b560 T _Init_yarp_api_node
000000000000b560 ? _Init_yarp_api_node
000000000000c180 T _Init_yarp_pack
000000000000c180 ? _Init_yarp_pack
0000000000014790 b __MergedGlobals
0000000000014790 ? __MergedGlobals
00000000000141f8 b __MergedGlobals
00000000000145f0 b __MergedGlobals
00000000000141f8 ? __MergedGlobals
00000000000145f0 ? __MergedGlobals
                 U ___stack_chk_fail
                 U ___stack_chk_guard
00000000000141f0 d __dyld_private
                 U _calloc
000000000000d3c0 ? _dump
000000000000d3c0 t _dump
000000000000d554 ? _dump_file
000000000000d554 t _dump_file
000000000000e120 ? _dump_input
000000000000e120 t _dump_input
                 U _free
000000000000d660 ? _lex
000000000000d660 t _lex
000000000000e39c t _lex_encoding_changed_callback
000000000000e39c ? _lex_encoding_changed_callback
000000000000d7f4 ? _lex_file
000000000000d7f4 t _lex_file
000000000000e1e4 t _lex_input
000000000000e1e4 ? _lex_input
000000000000e3c8 t _lex_token
000000000000e3c8 ? _lex_token
                 U _malloc
000000000000dce4 ? _memsize
000000000000dce4 t _memsize
000000000000dba0 t _named_captures
000000000000dba0 ? _named_captures
000000000000c2b0 ? _pack_parse
000000000000c2b0 t _pack_parse
000000000000e9d8 ? _pack_parse.cold.1
000000000000e9d8 t _pack_parse.cold.1
000000000000d900 t _parse
000000000000d900 ? _parse
000000000000da94 ? _parse_file
000000000000da94 t _parse_file
000000000000e7f8 t _parse_input
000000000000e7f8 ? _parse_input
000000000000df90 ? _parse_serialize_file_metadata
000000000000df90 t _parse_serialize_file_metadata
000000000000e440 t _parser_comments
000000000000e440 ? _parser_comments
000000000000e600 t _parser_errors
000000000000e600 ? _parser_errors
000000000000e6fc t _parser_warnings
000000000000e6fc ? _parser_warnings
000000000000de50 ? _profile_file
000000000000de50 t _profile_file
                 U _rb_ary_new
                 U _rb_ary_new_capa
                 U _rb_ary_pop
                 U _rb_ary_push
                 U _rb_ascii8bit_encindex
                 U _rb_bug
                 U _rb_cObject
00000000000147c8 B _rb_cYARP
                 U _rb_cYARP
00000000000147f0 B _rb_cYARPComment
                 U _rb_cYARPComment
                 U _rb_cYARPLocation
00000000000147e8 B _rb_cYARPLocation
00000000000147d0 B _rb_cYARPNode
                 U _rb_cYARPNode
                 U _rb_cYARPParseError
00000000000147f8 B _rb_cYARPParseError
                 U _rb_cYARPParseResult
0000000000014808 B _rb_cYARPParseResult
                 U _rb_cYARPParseWarning
0000000000014800 B _rb_cYARPParseWarning
                 U _rb_cYARPSource
00000000000147d8 B _rb_cYARPSource
                 U _rb_cYARPToken
00000000000147e0 B _rb_cYARPToken
                 U _rb_class_new_instance
                 U _rb_debug_rstring_null_ptr
                 U _rb_define_class_under
                 U _rb_define_const
                 U _rb_define_module
                 U _rb_define_module_under
                 w _rb_define_singleton_method
                 U _rb_eArgError
                 U _rb_eNoMemError
                 U _rb_eRangeError
                 U _rb_eRuntimeError
                 U _rb_eTypeError
                 U _rb_enc_find
                 U _rb_enc_from_encoding
                 U _rb_enc_from_index
                 U _rb_enc_str_new
                 U _rb_enc_str_new_cstr
                 U _rb_error_arity
                 U _rb_hash_aset
                 U _rb_hash_new
                 U _rb_id2sym
                 U _rb_intern
                 U _rb_intern2
                 U _rb_intern3
                 U _rb_obj_class
                 U _rb_raise
                 U _rb_str_new
                 U _rb_str_new_static
                 U _rb_string_value
                 U _rb_ull2inum
                 U _rb_usascii_encindex
                 U _rb_usascii_str_new
                 U _rb_utf8_encindex
                 U _rb_utf8_encoding
                 U _strcmp
000000000000e918 t _unescape
000000000000e918 ? _unescape
000000000000dcd8 ? _unescape_all
000000000000dcd8 t _unescape_all
000000000000dccc t _unescape_minimal
000000000000dccc ? _unescape_minimal
000000000000dcc0 ? _unescape_none
000000000000dcc0 t _unescape_none
0000000000003cdc T _yp_ast_new
0000000000003cdc ? _yp_ast_new
                 U _yp_buffer_free
                 U _yp_buffer_init
                 U _yp_encoding_utf_8
                 U _yp_node_destroy
                 U _yp_node_memsize
                 U _yp_pack_parse
                 U _yp_parse
                 U _yp_parse_serialize
                 U _yp_parser_free
                 U _yp_parser_init
                 U _yp_parser_register_encoding_changed_callback
                 U _yp_regexp_named_capture_group_names
                 U _yp_serialize
0000000000003c14 T _yp_source_new
0000000000003c14 ? _yp_source_new
                 U _yp_string_constant_init
                 U _yp_string_free
                 U _yp_string_length
                 U _yp_string_list_free
                 U _yp_string_list_init
                 U _yp_string_mapped_init
                 U _yp_string_source
0000000000003b1c T _yp_token_new
0000000000003b1c ? _yp_token_new
                 U _yp_token_type_to_str
                 U _yp_unescape_string
                 U _yp_version
                 U api_node.c
                 U api_pack.c
                 U dyld_stub_binder
                 U extension.c
```
</details>

> Would you mind trying on Ruby 3.2 and checking if you get the same result?

Here's some reinforcement that my build environment is messed up.  I'm having trouble getting `ruby-install` to build ruby 3.2.2 on my system.  I'm investigating further, and will close this issue when it turns out to be that.
